### ISSUE TITLE
Print all pages from multi-page TIFF file

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#1031]
From https://groups.google.com/g/imageglass/c/O7A5BQKOpGo/m/7obNLNFHAQAJ

I haven't been able to find this in documentation or previous issues, so my apologies if there's anything I've overlooked.

I can not find how to print all pages from a multi-page TIFF file. Am I missing something or is this option unavailable? I can only seem to be able to print the currently selected page.

----------

we have the same problem.
Is there planned a solution for the future releases?

In the moment we print out the TIFF over the Explorer Functionality.
highlight the tiff  in the explorer - right mousekey - print

**Comment by trickshooter** [comment]
This refers to ImageGlass_Moon_8.2.8.9_x64

As I already lined out here ([my post on issue #1091](https://github.com/d2phap/ImageGlass/issues/1091#issuecomment-850913699) ), there might be a **_printing_** issue with *.fax files as well - and it is as I already feared:

In case of **_printing_** the respective multipage TiffG4 file, there is still a severe issue:
Multipage TiffG4 files with a file extension of *.fax **DO NOT** offer to print **ALL** contained pages. Printing these files always only offers one single page (the current = last viewed) to be printed without an option to scroll through pages (as if the file is a single page file).

**The possibility of printing all pages of the \*.fax file is mandatory for the issue to be resolved!**

@d2phap: Possible solution / suggestion:
Behind the scenes, first copy *.fax file to %temp%\\\*.tif before passing it to the Windows standard photo print routine, because multipage printing of *.tif and *.tiff is handled correctly by Windows - whereas handling of *.fax files is **NOT.**

Greetz,
Christoph
