### ISSUE TITLE
onion skin

### ISSUE THREAD

**Issue by gontz** [d2phap/ImageGlass#1089]
Sometimes I have to model 3d a person and I would love to be able to put the photo over my 3d sculpture. 

An onion skin like function with always on top option would be really great.

**Comment by DEHNCKA** [comment]
It already looks like the "layers" tool. You can add, for example, one image to the first layer in this tool, then switch to another (in the main view area) and add it to the second layer. Only here's how to shift them relative to each other (in order to achieve a match when superimposed) - remains a mystery to me. It's already something about the image editor, and not about the viewer.

**Comment by d2phap** [comment]
Close this because not planned
