### ISSUE TITLE
ImageGlass doesn't see all pages of a multipage tiff

### ISSUE THREAD

**Issue by iDm1** [d2phap/ImageGlass#1113]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Open a multipage tiff file.
2. Enable page selection overlay with P key if it's not enabled.
3. ImageGlass shows only 1/1.

### Actual behavior:
ImageGlass shows only the first page.

### Expected behavior:
ImageGlass should be able to switch between the pages.

### Additional context:
Here is an example tiff [test.zip](https://github.com/d2phap/ImageGlass/files/6816656/test.zip)

**Comment by fire-eggs** [comment]
Thanks for the report. Confirmed.

I'm editing the title as IG _does_ support multi-page tiffs (see issues #1077 and #1094) but for some reason fails to handle this TIFF file.

Can you tell us which program was used to produce this file?

XnView and IrfanView both see both pages.

ImageMagick 7.0.11-2 is able to see both pages, but does produce warnings:
```
magick: Unknown field with tag 770 (0x302) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
magick: Unknown field with tag 20752 (0x5110) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
magick: Unknown field with tag 20753 (0x5111) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
magick: Unknown field with tag 20754 (0x5112) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
magick: Unknown field with tag 20752 (0x5110) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
magick: Unknown field with tag 20753 (0x5111) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
magick: Unknown field with tag 20754 (0x5112) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
```

**Comment by iDm1** [comment]
Looks like this happens with all TIFF's created with NAPS2 https://www.naps2.com/ in multipage mode.
But other software, including even old Windows Photo Viewer, handles them correctly.

**Comment by iDm1** [comment]
> ```
> magick: Unknown field with tag 770 (0x302) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
> magick: Unknown field with tag 20752 (0x5110) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
> magick: Unknown field with tag 20753 (0x5111) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
> magick: Unknown field with tag 20754 (0x5112) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
> magick: Unknown field with tag 20752 (0x5110) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
> magick: Unknown field with tag 20753 (0x5111) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
> magick: Unknown field with tag 20754 (0x5112) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
> ```
This may be just some additional metadata, which ImageMagick doesn't support. Maybe OCR data.

**Comment by trickshooter** [comment]
Hint: Rename the above attached "test.tiff" to "test.tif" '(only one f in the extension) and the functionality is restored as desired.

Solution: ImageGlass needs to handle files with *.tif, *.tiff, *.fax, *.jfx extensions in the same way / similarly as they can potentially all contain multipage TIFF files (e.g. among others "CCITT Fax Group 4 compressed")!

**Comment by d2phap** [comment]
Add multipages support for TIFF, FAX.
You can try the latest build: https://imageglass.org/moon

**Comment by trickshooter** [comment]
This refers to ImageGlass_Moon_8.2.8.9_x64

OK, multipage support for extension *.tif, *.fax and *.tiff now works flawlessly as desired regarding the pure **_viewing_** functionality (only). Thank you so much for implementing these additional file extensions! BUT (unfortunately)....

(for all the below cases we're always talking about a binarily identical TiffG4 file that simply gets renamed to different file extensions)

As I already lined out here ([my post on issue #1091](https://github.com/d2phap/ImageGlass/issues/1091#issuecomment-850913699) ), there might be a **_printing_** issue with *.fax files as well - and it is as I already feared:

In case of **_printing_** the respective multipage tif file, there is still a severe issue:
*.tif as wells as *.tiff are handled correctly (the printing dialog correctly offers all pages to be printed or selected or cycled through (in the printing preview), BUT...

**_...NOT so with *.fax files!_** Printing always only offers one single page (the current = last viewed) to be printed without an option to scroll through pages (as if the file is a single page file).

**The possibility of printing all pages of the \*.fax file is mandatory for the issue to be resolved!**

@d2phap: Possible solution / suggestion:
Behind the scenes, first copy *.fax file to %temp%\\\*.tif before passing it to the Windows standard photo print routine, because multipage printing of *.tif and *.tiff is handled correctly by Windows - whereas handling of *.fax files is **NOT.**

Greetz,
Christoph

**Comment by d2phap** [comment]
@trickshooter for your issue, refer to #1091
