### ISSUE TITLE
Rotate Image -> Save Image As.. Produces corrupt, unreadable image

### ISSUE THREAD

**Issue by PxCommoner** [d2phap/ImageGlass#1120]
### System information:
 - Windows OS version: 
 Edition	Windows 10 Pro
Version	21H1
Installed on	‎07/‎31/‎2021
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

 - ImageGlass version: 
8.2.6.6 (Portable)

### To Reproduce
1. Open image
2. Rotate Image
3. Save Image As..
4. 

### Actual behavior:

Saved Image is unreadable

### Expected behavior:

Image should still be readable

**Comment by fire-eggs** [comment]
Not reproducible when opening a JPEG, rotating, and saving as JPG, PNG, or TIFF.

Please specify the image format you loaded and the image format you saved to.

**Comment by PxCommoner** [comment]
https://youtu.be/6eR54dWZOjU
![SCAN0007](https://user-images.githubusercontent.com/26192313/127810158-f6120255-927b-491c-b7a0-0c30b9dff63e.JPG)
![SCAN0008](https://user-images.githubusercontent.com/26192313/127810159-07c1e916-43c6-471f-ab08-c9cf6b3e7011.JPG)


The issue may be file specific - I scanned these files from my printer. Downloading and saving them should hopefully be identical to the ones on my flash drive.

**Comment by fire-eggs** [comment]
Wow! Thanks for the video - that was what finally let me repro the bug!

This is _really_ stupid, but the problem happens because the file extension on your "original" files is "JPG", not "jpg"!

That is, if I change your file extensions to "jpg", no problem. For some reason the uppercase vs lowercase makes a difference! Mixed case (e.g. ".jPg") also fails!!

So it's definitely a bug but there's a workaround...

Much obliged for the extra effort!

**Comment by d2phap** [comment]
Please try the latest build of IG Moon which is to attempts to fix this issue.
https://imageglass.org/moon
Note that, the thumbnail bar is flashing when the app is busy, I will fix later.
