### ISSUE TITLE
Exif data as overlay over the image

### ISSUE THREAD

**Issue by shockergit** [d2phap/ImageGlass#1188]
is it posiible to show the exif data as a overlay over the instead of a seperate tab.

**Comment by d2phap** [comment]
ImageGlass currently does not support overlay Exif tool

**Comment by dajotim937** [comment]
Shame.
Honeyview has a nice way to show EXIF metadata over image.
And it's fast to overview because I don't need that excessive amount or EXIF metadata from exiftool and don't neet to open any new windows or something. Just hit "tab" button and it shows everything.

![Image](https://github.com/user-attachments/assets/0f3258b6-9faf-454d-8254-eee27fbacd1b)
