### ISSUE TITLE
Better explanation about the Spider Service

### ISSUE THREAD

**Issue by vivadavid** [d2phap/ImageGlass#1250]
Hi,

I've just read the information about the Spider Service (" This service shares device IP (none of your personal information is accessed) with Spider.com customers to pass traffic through your device") and I'm still not sure what the implications are (also I'm not technical, but my IP looks like personal information). I understand my IP is tracked and shared: but to whom and to what purpose? I think the whole thing should be better explained, so that people can decide what to do. It certainly brings me some concerns.

Thanks for your time and have a nice day!

**Comment by d2phap** [comment]
Hi @vivadavid 

You can find out the details here: https://imageglass.org/docs/spider-service, and https://imageglass.org/privacy.

If you are not sure, you can just remove it without a second of thinking.

**Comment by vivadavid** [comment]
> Hi @vivadavid
> 
> You can find out the details here: https://imageglass.org/docs/spider-service, and https://imageglass.org/privacy.
> 
> If you are not sure, you can just remove it without a second of thinking.

Thank you for your quick reply. It might be my problem, but I did read all this information, and yet I don't know what Spider Service does with my data: that's why I wrote my message above. Is it just an ad provider?

**Comment by d2phap** [comment]
Spider collects IP address to use and improve their services. You can see the use cases on their website: https://www.spider.com

![image](https://user-images.githubusercontent.com/3154213/150506251-d87fbf91-523f-4dc6-8894-dd7f31346797.png)

**Comment by vivadavid** [comment]
> Spider collects IP address to use and improve their services. You can see the use cases on their website: https://www.spider.com
> 
> https://www.spider.com/blog/what-are-private-residential-proxies-and-how-do-they-work
> 
> > The most popular use-cases for private proxies are business and personal interests: commercial needs used by companies include ad verification on websites or bulk collection of travel pricing; while for personal use it usually entails strict high level anonymity when browsing the web.
> 
> ![image](https://user-images.githubusercontent.com/3154213/150506251-d87fbf91-523f-4dc6-8894-dd7f31346797.png)

Thanks for the info!

**Comment by AntoninCurtit** [comment]
_Message transfered from release page dicussion_

Hi !
Thanks for this new interesting release ! Though, I have big concerns about the Spider service.

- First, the fact that the checkbox is enabled by default, which might be problematic and non-GDPR compliant. (This allegation is partially linked to next point and may be or not relevant based on your answer)
- [ ] Note to me : To read the privacy policy to see if IP can be linked with eventually collected datas.

- [x] (answered) Next, what datas are shared with Spider ? "This service shares device IP (none of your personal information is accessed) with Spider.com [...]"
Only IP is shared ?
**Answer : Yes** and IP doesn't seems to.be considered "personal" as long as they can't be linked to others informations.

- [ ] Then, the last part of the previous sentence "[...] customers to pass traffic through your device." is quite, strange. What Spider is doing exactly ?

I expect from a photo-viewer service to... Not make the coffee, and just be a photo-viewer service. 😉

I also want to points that I see the amount of work you made during years, that I understand that you need a "reward"/counterpart and users donations aren't enough, and that I see you take seriously and tried to be transparent with the Spider service.

Thank you !

**Comment by d2phap** [comment]
Hi, I decided to remove the Spider service from ImageGlass since all people don't like it. Instead, I will find the suitable model for the app.

Currently, version 8.4 is already removed from download. ImageGlass Store version is not affected.

I will work on an update this weekend.
Thank you!
Phap

**Comment by vivadavid** [comment]
> suitable

Thank you! I hope you find a good model for your app!

**Comment by d2phap** [comment]
Hi, the version 8.5 is already released:
- No more Spiderman no way home
- Options: Start with OS and Continue running background is unset by default
- Others features and bugfixes are same as v8.4 (which was already withdrawn)

Thank you!

**Comment by AntoninCurtit** [comment]
We're sorry that you had to revert your work, but I'm happy the way you handled that. Thanks to you !

**Comment by d2phap** [comment]
I'm also sorry for that bad idea, too.
Thank you

**Comment by Otiel** [comment]
Thanks for listening to the community. I hope you find a good model to sustain your work without affecting users, particularly those who are less tech-savy or not aware of tracking practices to watch for.

Thank you for your hard work ❤️

**Comment by spiderwest** [comment]
I am the CEO at Spider.com. We vet all of our users, you likely know who our customers are, they are large fortune 500 companies. Businesses that need pricing on Amazon products or positions in Search Engine results. The large enterprises with all this data don't make it easy to gather at scale. So by using a few queries from thousands of different IPs we can use the collective wisdom of the crowd. Secret shoppers have exist for about 500 hundred years and pre-date the Internet. You use this service every time you shop at a grocery store. The price of a bag of rice or can of beans will be reasonable to competing grocery stores. 

The great news is we are not processor or memory heavy. In fact we don't compute anything local on machines and the bandwidth we use is the equivalent to downloading a few images. We sponsor projects to help developers and keep software free. We all know that software takes hundreds of hours to develop and maintain, so symbiotic relationships are good for the community. 

We always require disclosure and being upfront with users. We require an informed decision on the part of the software's user. I am happy to answer questions about how Spider works. I can assure you we are GDPR compliant, we don't care about collecting user data we only gather data that is publicly available online about products and companies from public facing websites.

**Comment by MoemenShahawy** [comment]
> I am happy to answer questions about how Spider works.

nah bro we good. the spider thing been deleted for good. this is an image viewer and it's good for what it does. I'm out the moment it starts to get complicated and have too much background stuff like spider and windows start service (why would I want an image viewer in queue to slow down my startup and run in the background while I'm gaming or working is beyond me)

If it works don't try to fix it.

**Comment by ConstantineRudenko** [comment]
>The large enterprises with all this data don't make it easy to gather at scale. So by using a few queries from thousands of different IPs we can use the collective wisdom of the crowd.

https://github.com/d2phap/ImageGlass/issues/1250#issuecomment-1021423957

So basically you are redirecting your requests to the websites (e.g. shops) you want to scan through the PCs of the users (with their permission) so that it doesn't look like all of the requests are coming from the same place, thus getting around the restrictions for number of requests per user.

I think different people would have different opinions on how appropriate this is (which is often the case for anything), but I personally wouldn't mind this type of software monetization. The problem is - until I saw your explanation, I had zero idea of what spider does, and for what purpose. It would be a gross understatement to say, that without a clear explanation like this the service looks shady at best.

I think it would be beneficial to your business, the developers who might consider integrating it, and indirectly - the end users (by the virtue of empowering the developers to dedicate more effort towards the software as it begins to generate some income), if you added this **concise** and most importantly **simple** and clear **explanation** of what the service on the front page of your website, and encouraged the software developers who choose to integrate to to link that very explanation on their websites.

Currently what I see is 
```
The Greater Grid Proxy Network of Residential & Mobile IPs

Scrape any data from a private network of residentials IPs. Reduce failure rate, blocks, and cloaking
```

This does NOT encourage my trust. In fact, it sounds like something I want to be as far removed from as possible. And to make it even worse, it sounds like "a private network of residentials IPs" is what is being scraped for data. **I will be scraped for data if I install this.**

**Comment by ctaetcsh** [comment]
> nah bro we good. the spider thing been deleted for good

Except it wasn't. The latest release on the website has it again. I have been completely oblivious to this the whole time so finding out about it now was an unwelcome surprise. 

@spiderwest I appreciate you coming into this thread to address this, because as far as I can tell your service uses peoples computers to scrape websites, piggybacking off of their legitimate connection to bypass bot filters. If I'm off base here please do clarify because this is extremely concerning.

ImageGlass has been one of my staple applications on Windows for a while now. It's simple, just an image viewer without the extra BS. Except not anymore I guess. I don't think I'm off base here because the reactions of people I've talked to have ranged from "Thanks for letting me know, I'm not updating" to "F*** ImageGlass, I'm uninstalling and never using it again, they are scum". 

@d2phap I would really like to discuss this further, either in this issue or in your Discord, where I have already joined. :)

**Comment by MoemenShahawy** [comment]
> > nah bro we good. the spider thing been deleted for good
> 
> Except it wasn't. The latest release on the website has it again. I have been completely oblivious to this the whole time so finding out about it now was an unwelcome surprise.

So it was always there, but way down on the download page. They always have a "clean" installer called Kobe, and another with Spider

What they did with the latest version, is they made the Spider installer #1 in the download choices, and the clean installer #2

which IMO is scummy
I just want a simple clean image viewer. No spider, no autorun service, no BS. 
Is it that hard to keep things as they are??

**Comment by ctaetcsh** [comment]
> I think it's quite obvious: color, Learn more link, privacy link,... Recently, I've even added a link to help people understand the difference between the release codes: Don't know which release to download...

The page that explains the differences between the versions is very helpful and thank you for adding it. However, the Learn More link next to the Spider downloads takes you to a page that doesn't explain what Spider does on the users computer. It just says "ImageGlass Spider is a special release of ImageGlass, collaborates with the Spider to create a full-featured image viewer and provide enterprises the on-demand data collection for analysis.". 
Also, and I'm not sure if this is just a bug, but when going to the release page sometimes the Kobe downloads will be first and sometimes the Spider downloads will be first. 

> ImageGlass does not have auto-updater since version 1.0, it's not because of the Spider version so that I don't want to implement it. If you check the project [V9 - Beta 2](https://github.com/d2phap/ImageGlass/projects/12), you will see there is a plan to improve it. But honestly, I'm still not sure how to implement it. As ImageGlass is open source, I'm hoping somebody can help me with a PR.

I'm referring to the popup that appears on launch if you have an outdated version of ImageGlass, and will take you to the latest releases download page if you click Download. I and a handful of my friends that also use ImageGlass have developed muscle memory to just download the latest thing and run the installer. This is partly why I think I had such a strong reaction thinking "Oh Its just a new release of ImageGlass codenamed Spider, Ill upgrade", without reading the fine print. 

> Conclusion, I always say this: If you don't like the ImageGlass Spider, use ImageGlass Kobe.

This is what I'm planning on doing as I still really like your program and will still recommend Kobe. I appreciate you taking the time to respond to this issue.

**Comment by BugFixesAndPerformanceImprovements** [comment]
> I just want a simple clean image viewer. No spider, no autorun service, no BS. 
> 
> Is it that hard to keep things as they are??

For those who are interested in just that, have a look at JPEGView. Very fast to open, very simple and no service or shady things installed.
