### ISSUE TITLE
After rotate, can't save the image. 

### ISSUE THREAD

**Issue by vuslatx** [d2phap/ImageGlass#1273]
### System information:
 - Windows 11 Pro With Latest Update since now.
 - ImageGlass version: 8.5 portable

After rotate, can't save the image. 

I tried to explain my problem with video:

http://tuskolik.com/1494.mp4

https://user-images.githubusercontent.com/3154213/169681115-9ebe4ede-7343-45d8-a528-4af94742ab96.mp4

I tried these:

Uninstall and reinstall, portable mode, non-portable mode, previous versions, but not solved. 

Also: it doesn't change if i change folder location, local disk c, local disk d, desktop etc.

But if i press ctrl+s, it's okay.

**Comment by fire-eggs** [comment]
Looks like the "save at exit" case was missed.

For this situation [where you have more than one image in the folder] the save _should_ happen when you go to the next image.

**Comment by Shituation** [comment]
Why not making it save instantaneously for rotation? sometimes you just need to rotate one image and you don't have anymore in the folder so you just close the app; this doesn't save the rotation.

**Comment by fire-eggs** [comment]
>  sometimes you just need to rotate one image and you don't have anymore in the folder so you just close the app; this doesn't save the rotation.

Which I admit is a bug. Not saying otherwise, just suggesting a possible workaround.

>Why not making it save instantaneously for rotation?

Reasonable question, as long as the "save image after rotating" option in Settings \ Edit was respected.

Since ImageGlass can't write using all the image formats it can read, it might not be desired to auto-save. For myself, I'll rarely want to save a rotation, I'm just looking at the image from a different perspective.

**Comment by Shituation** [comment]
What about an option to turn on or off the "instantaneous save" and some lines of code to tell the app that "if the source image cannot be saved because the program doesn't support saving in that format, show the user a warning about transcoding the image to JPG" or something like that?

IMHO the most used formats are jpg, jpeg, bmp, png and not much more. Gifs maybe? but those are usually animated. I think most of the userbase would appreciate the instant save option with no collateral damage.

**Comment by d2phap** [comment]
@elcosomalo1 because it's a bug. In v8.5, I tried to fix this issue, but this seems remain.

**Comment by EarlMobileh** [comment]
When facing this problem I figured out that setting the amount of pictures in the ImageBooster cache to zero fixed the problem and "saving after rotation" does work fine.

**Comment by Shituation** [comment]
I simply stopped using it. Its dangerous and unpredictable not suited for daily use.
I found https://github.com/easymodo/qimgv and Im happy with it. Doesnt suffer from random image corruption. 
The dev here is still offering this soft with no warnings even when he knows the issue.

**Comment by d2phap** [comment]
This issue should be fixed in the latest build of ImageGlass Moon 8.7: https://imageglass.org/moon.

The saving behaviors are also changed:
- When user make a change to the viewing image, ImageGlass will show a warning message when they want to override it.
- When user make a change to the viewing image and then exit the app, or view another image, ImageGlass will show a prompt to ask user if they want to save the change or not.

![image](https://user-images.githubusercontent.com/3154213/225963268-33deedb8-c2fb-464b-8dce-68a258bff66d.png)


![image](https://user-images.githubusercontent.com/3154213/225963039-a4009770-a590-4a67-bc5e-00d6293810a3.png)
