### ISSUE TITLE
Public opinion poll about Spider service

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#1277]
Yes, it's about the Spider service again, **but don't worry, I have a solution, and I want to hear your opinions**.
This is my last topic about the Spider service. I want to create this public opinion poll to collect your feedback.

_ | Details
-- | --
From | January 28, 2022
To | February 03, 2022
At | [ImageGlass GitHub](https://github.com/d2phap/ImageGlass/issues)

## The old implementation in v8.4:
- Spider was integrated into **MSI** and **portable x64 releases** as an opt-in option.
- Users were only notified through the First-launch configuration dialog when they launched the app. They had no option to disable it here.
- The Spider service was auto-started after 5 seconds when the process `ImageGlass.exe` ran.
- Users had an option to disable it in the Settings dialog.
- Users could permanently remove it by deleting the `bs-sdk.dll` file as instructed on the ImageGlass documentation page.

## The proposal:
- I am going to create a **new ImageGlass app** called **ImageGlass Spider**, hosted in a separate GitHub repo (it's also open source).
- The Spider service will be **only** integrated into the **ImageGlass Spider** app, in the new repo.
- All releases and source code published at https://github.com/d2phap/ImageGlass will not contain the Spider service.
- The ImageGlass Spider app will also be listed on ImageGlass website as one of the 6 options for user to download:
  - ImageGlass Kobe - Store version
  - ImageGlass Kobe - MSI x64
  - ImageGlass Kobe - MSI x86
  - ImageGlass Kobe - Portable x64
  - ImageGlass Kobe - Portable x86
  - ImageGlass Spider
- When users download ImageGlass Spider on ImageGlass website, they will be redirected to the ImageGlass Spider page with information about the app.
- The Spider service in ImageGlass Spider will be implemented as an opt-out option:
  - Users will have to accept the privacy agreement dialog before they can launch the ImageGlass Spider app, in the First-launch configurations dialog. They will have an option to opt out the service.
  - The Spider service will auto-start after 5 seconds when the process `ImageGlass.exe` runs.
  - Users have an option to disable it in the Settings dialog.

## The decision
- Waiting for your opinions. I'm happy to answer any questions about the implementation, and you can ask @spiderwest - CEO of Spider.com about how Spider works as well.
- This is probably my best effort (and try) to satisfy all sides while I can earn an amount to actualize my ideas about ImageGlass in the future.
- I'll update it here after the poll ends, **on February 04, 2022**.

Happy Lunar new year!

**Comment by DEHNCKA** [comment]
50/50

You yourself spoke about the inadmissibility of "inflating" the program. I think this is it. I also understand that I do not need problems with the law and the authorities, so I will not support the Russian-language translation (and, if necessary, the design themes) for "ImageGlass Spider". I will only support the regular version of ImageGlass. I have a concrete example from life when a person just voiced an opposition film and got behind bars. Specifically about the situation here: we are showing opposition towards users.

Why am I thinking this way? Because everything that is made by a person or a group of people, even everything that exists in this world, this also applies to phenomena - has two sides of the coin. This can serve both for good and for harm. No matter what they tell us about security, about preserving rights, about "filtering clients" and so on, and so on... - there will always be those (or "that") who will find a way to use the creations of the creators to harm. By trickery. But, there is always a choice, this choice depends on us.

Neither good nor evil - they cannot interfere in the course of events without our consent. The main thing from us is to give consent at the right time, in the right place, following the truth and listening to ourselves, and not to "good" or "bad" characters.

**Comment by DEHNCKA** [comment]
As long as I have the opportunity, I will support financially, but in other ways, not through "Spider".

**Comment by cihe13375** [comment]
Not sure on this. Personally I don't see a reason to use the Spider version after such split --- like why run some (potentially risky) bloatware on my computer when I can choose not to (also I don't think services like Spider are beneficial to the Internet ecosystem as a whole). If I want to sponsor the project I'd like to donate directly (by MS Store or direct purchase), which is better for both of us.

I also completely understand that not a lot of people will donate voluntarily (to be honest, this also applies to me, I definitely considered "oh I want to donate to this at some point" but didn't do so until now lmao), so it's better to have some motivation pushing users when they're hesitating on "donate or not...". I think a possible approach for this is spliting ImageGlass into "Standard" and "Extra" version: the Standard version is similar to the current one (like a enhanced "Windows Image Viewer" thing), while the Extra version (it can be close-sourced) includes some advanced but not essential features (e.g. simple photo editing, better support and simple editing to vector images, better upscaling algorithms, etc.)

I'm not sure about cracks though, it seems that they always exists. But at least personally I'll pay for it provided that the price is reasonable (current price on MS Store seems good to me).

**Comment by vivadavid** [comment]
Hi! I think the proposal is quite reasonable. The key point is that users are informed and can decide.

**Comment by d2phap** [comment]
Thanks all for your feedback.
I decide to go with the proposal implementation above, and also continue monitoring the feedback for future adjustment. ImageGlass will always have free-and-clean version as it is.
