### ISSUE TITLE
Thumbnails are not cached

### ISSUE THREAD

**Issue by blablablabla** [d2phap/ImageGlass#1292]
### System information:
 - Windows OS version: Win 10 1809
 - ImageGlass version: 8.5.1.22 x64 [Portable]

### To Reproduce
1. Open up a file in a folder with many HEIC files
2. Wait for thumbnails to generate
3. Close IG and reopen
4. Thumbnails are generated once again

Since opening a single HEIC image takes a few seconds (one-two seconds per image on Ryzen 9 5900X with 4.8 GHz turbo) as per [this](https://github.com/d2phap/ImageGlass/issues/995) issue, I wanted to browse the HEIC photo library using the Thumbnail bar.

It seems though that the thumbnails for the photos are generated each time ImageGlass is run and they are not cached from one run to another.
Also ImageGlass does not generate thumbnails for pictures which are not currently visible in the thumbnail bar (i.e. if you scroll down in the thumbnail bar, you have to wait for another batch to load). For a bar with 66 images, the thumbnail generation takes about ~22 seconds using about 4-6 cores on the aforemetioned Ryzen).

Thanks!

**Comment by fire-eggs** [comment]
Thumbnails have never been cached, switching to 'feature request'.

**Comment by d2phap** [comment]
This issue is implemented in the ImageGlass Moon v9.0 beta 1: https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514.
The cached thumbnails are stored in `ThumbnailsCache` folder. Maximum cache is set to 100 MB.

![image](https://user-images.githubusercontent.com/3154213/169642381-9b4786a5-10cf-457b-affb-d466d0f12b23.png)
