### ISSUE TITLE
Follow Windows sorting settings

### ISSUE THREAD

**Issue by Baegus** [d2phap/ImageGlass#13]
All the "Image loading order" options work perfectly, but the only one I'm missing is something like "Follow ordering of containing folder".
For example if the images are located in a folder sorted by date, ImageGlass would order them the same way.

**Comment by Kosyne** [comment]
+1 Hope to see this implemented.

**Comment by d2phap** [comment]
Done

**Comment by ubershy** [comment]
Hello.
The patch implements Windows way of sorting by name, which is good, but I don't think this is what the author of the issue meant. So I don't think that this issue should be closed.
I think the author meant that ImageGlass should be able to show files in the same order that is chosen in Windows file Explorer. For example, if in Windows file explorer files are sorted by Date then ImageGlass should show them by Date. If in Windows file explorer files are sorted by Size then ImageGlass should show them by Size. Just like in Windows Photo Viewer. But only when new order option "Follow ordering of containing folder" is chosen.
I came up with alternative name for this option - "Follow Windows Explorer order".
ImageGlass is a nice program. But I miss such option so much. I would be really glad if you could implement it.
Thanks.

**Comment by d2phap** [comment]
Thanks @ubershy 
I'm aware this misunderstanding and the fix is just follow the sorting style of alphabet in Windows File Explorer, not the sorting option.

There is already an open issue about this: #139 

I also found some codes but I haven't tested yet.
https://www.experts-exchange.com/questions/26120455/How-to-get-Files-folders-Sort-order-in-Windows-Explorer-window-in-C.html
