### ISSUE TITLE
Copy image data does not copy transparency correct

### ISSUE THREAD

**Issue by bjornsyse** [d2phap/ImageGlass#1305]
### System information:
 - Windows OS version: Windows 10 Version	10.0.19044 Build 19044
 - ImageGlass version: 8.5.1.22

### To Reproduce
1. Open Transparent image
2. Copy image data (CTRL+C)
3. Open image data from Clipboard (CTRL+V)

### Actual behavior:
Alpha channel is lost, and replaced with white. 

### Expected behavior:
Alpha channel is retained. This is how it works if I copy from a layer in for example photoshop.

**Comment by d2phap** [comment]
Add support for copy/paste transparency in the latest build of ImageGlass Moon 8: https://imageglass.org/moon.
So far it works with Paint.NET, MS Word, Power Point, Excel, MS Edge, Chrome,..

Please note that, Because the Windows clipboard data is really dirty and inconsistent, and some software create its own way to copy and paste image data, this implementation is just try to cover all the popular formats as the below screenshot. While `PNG` and `CF_DIB` contain image transparency, the clipboard-reader software should support reading from `PNG` and `CF_DIB` to retrieve the bitmap with transparency.


![image](https://user-images.githubusercontent.com/3154213/169303510-501990b3-d44d-4778-b46c-c1981e71a6ef.png)


Debug with InsideClipboard:

![image](https://user-images.githubusercontent.com/3154213/169304177-91ae19e7-02e5-4a9f-9b1f-0d361eff4b5c.png)
