### ISSUE TITLE
Wrong install location

### ISSUE THREAD

**Issue by why0why0why** [d2phap/ImageGlass#1365]
### System information:
 - Windows OS version: windows 10 20H2
 - ImageGlass version: 8.6.7.13

### To Reproduce
1. open installer
2. change install location to D:/~1/ImageGlass
3. install

### Actual behavior:

it has been installed to default install path C;/program files/ImageGlass

### Expected behavior:

it should be installed to D:/~1/ImageGlass

### Additional context:

I tried to install in all of my three computers and they showed in the same way

**Comment by d2phap** [comment]
Fixed for `ImageGlass_Kobe_8.6.7.13_x64.msi`! You can download again.

**Comment by darkvertex** [comment]
@d2phap I noticed the hash in winget was out of date so I fixed it: https://github.com/microsoft/winget-pkgs/pull/63751

Otherwise winget was raising a warning that something might be sketchy:
![image](https://user-images.githubusercontent.com/941331/174126321-62f32011-1e6a-48ba-b587-a620645c9520.png)

**Comment by d2phap** [comment]
That's awesome!
Thank you, @darkvertex
