### ISSUE TITLE
[Feature Request]Custom Configuration Path / Configuration Export

### ISSUE THREAD

**Issue by TheCGDF** [d2phap/ImageGlass#1372]
### Is your feature request related to a problem? Please describe.

In old versions, the configuration was being stored in a separate folder(`C:\Users\AppData\Roaming\Image Glass`).
I have multiple computers and I used to back up the configuration folder to make all computers consistent.
But the latest version stores the configuration into the installed path,
it makes me confused that which ones need to be backed up.

### Describe the solution you'd like

Allow user to custom the configuration location. (I'm using a tool to sync a folder between computers, I can set the configuration path into the synced folder.)

### Describe alternatives you've considered

Or add a Configuration Export function to generate something like `config.7z`, and can be imported easily.
(Of course these two ways have no conflict and can exist at the same time.)

**Comment by d2phap** [comment]
If you installed for "Only for me", the config will be saved in the folder you choose (if it has write permission). If you choose "Everybody", it will use `C:\Users\AppData\Roaming\ImageGlass` because IG does not have permission to write to Program Files folder (admin required).

![image](https://user-images.githubusercontent.com/3154213/174774460-8e26f46c-833c-4887-8552-0044c3ac82f4.png)

If you run ImageGlass as admin, it will use the installed folder as config dir, because it can write config file here.

But I like the idea about detect and restore config file.

**Comment by TheCGDF** [comment]
> If you choose "Everybody", it will use `C:\Users\AppData\Roaming\ImageGlass` because IG does not have permission to write to Program Files folder (admin required).
> 
> If you run ImageGlass as admin, it will use the installed folder as config dir, because it can write config file here.
> 

I chose "Everybody" and did not run as admin, but ImageGlass used the installed folder.
Older versions before `8.6.7.13` was using `C:\Users\AppData\Roaming\ImageGlass`.

**Comment by d2phap** [comment]
ImageGlass uses its installed folder when it has write permission, otherwise it will use the AppData folder. I will not change this.
