### ISSUE TITLE
Slideshow in window mode (not fullscreen)

### ISSUE THREAD

**Issue by mbhkoay** [d2phap/ImageGlass#1394]

**Comment by d2phap** [comment]
It's not official supported but since [version 7.5](https://github.com/d2phap/ImageGlass/releases/tag/7.5.1.1), all window modes can be combined to create a new window mode:
- Windowed slideshow (F11 -> F12 -> F11)
- Frameless windowed slideshow (F11 -> F12 -> F11 -> F10)
- Window-fit slideshow (F12 -> F9 -> F10)
- Frameless Window fit (F10 -> F9)

**Comment by mbhkoay** [comment]
This is great! It's exactly what I imagine.
