### ISSUE TITLE
windows thumbnails sometimes don't generate

### ISSUE THREAD

**Issue by playmobilmeister** [d2phap/ImageGlass#1402]
### Description
ever since my last install of IG, my windows thumbnails behave strangely. JPG for example, sometimes get thumbnails and sometimes don't. example:

![image](https://user-images.githubusercontent.com/33288162/182035057-3b4d4ee4-ea5b-4e7f-a47c-5a8faadc6350.png)

This also happens with .png btw. This happens in multiple folders, but not all of them, but I could not figure out the pattern.
### Version
I just updated to the latest version (8.6.7.13) but the issue persists. 
Windows version 21H2 (Home)

**Comment by d2phap** [comment]
Honestly, I have no idea.
Can you just try deleting thumbnails cache and rebuilding the thumbnails again: 
https://www.windowscentral.com/how-reset-thumbnail-cache-windows-10

**Comment by playmobilmeister** [comment]
No, this did not work unfortunately

**Comment by donatopace** [comment]
Hello,
you can try to increase the folder cache size,
this is the registry key that also speeds up image loading.
If that's not enough, you can clear the "thumbnail" cache with programs like CCLEANER etc.
obviously restarting before checking if the problem is solved and if necessary by forcing the folder update with the "F5" key

[Max Cached Icons.zip](https://github.com/d2phap/ImageGlass/files/9491971/Max.Cached.Icons.zip)

**Comment by playmobilmeister** [comment]
This actually worked, thanks ! I added the digit '1' to the left of the existing number in the said registry entry, and used Glary Utilities to clear the thumbnail cache, and voila !
