### ISSUE TITLE
Software dependency checker

### ISSUE THREAD

**Issue by 8uddha5an** [d2phap/ImageGlass#1445]
I installed ImageGlass on a computer and wasn't aware that we didn't install .NET Framework 4.8 on it. When I opened up ImageGlass, it stated that it needed the .NET Framework installed and it needed the dependency to run. 

Please add a .NET Framework checker so that we can use ImageGlass more smoothly in the future.

**Comment by d2phap** [comment]
@8uddha5an 

> When I opened up ImageGlass, it stated that it needed the .NET Framework installed and it needed the dependency to run.

This is framework's level check so I cannot implement this. But isn't it working like you mentioned?

Also, since v8.0, ImageGlass has been using .NET Framework 4.8 which is announced here ~2y ago:
https://imageglass.org/news/announcing-imageglass-8-0-kobe-70

FYI, ImageGlass 9.0 will use .NET 6.0 as I announced since v8.3 released: https://imageglass.org/news/announcing-imageglass-8-3-73
