### ISSUE TITLE
clickable areas in the screen [windowed mode/full screen]

### ISSUE THREAD

**Issue by diieg707** [d2phap/ImageGlass#1468]
following the request #648 i'd like to propose to add clickable areas in the screen for windowed mode and full screen

windowed mode: 
![2022-12-20 00_43_43-Sandboxie_BorderWindow - Copy](https://user-images.githubusercontent.com/54504707/208582900-c03debac-39ce-4d16-afe3-8cb409d12bc5.jpg)

windowed mode 33% of below picture area is reserved for previous/next clickable area, the rest above is for full screen double click (keeping #648 request),

![2022-12-20 00_43_43-Sandboxie_BordefffrWindow - Copy](https://user-images.githubusercontent.com/54504707/208584547-d051e0e8-81cd-4fa7-b436-973bc48dc8da.jpg)

on fullscreen mode, upper right corner exits full screen, below area add previous and next clicable area, and the rest resignate as left click = next file, right click = previous file.

**Comment by diieg707** [comment]
also add once the mouse is over the previous/next are the mouse cursor is changed to left or right arrow, similar to faststone image viewer

**Comment by d2phap** [comment]
You can enable the navigation buttons in Settings > General > Viewer (ImageGlass 8):
![image](https://user-images.githubusercontent.com/3154213/209430852-a702f469-e129-4a06-a365-1e56baacb5fb.png)

For left/right click action, you can do it in ImageGlass 9 as described here: https://github.com/d2phap/ImageGlass/issues/991#issuecomment-1238130837

I would like not to implement the other requests because it's too detailed, and all of them can be replaced by the hotkey.
