### ISSUE TITLE
image saturation difference between jpg and lossless jxl

### ISSUE THREAD

**Issue by karoberts** [d2phap/ImageGlass#1487]
### System information:
 - Windows OS version: Windows 10 Pro 22H2
 - ImageGlass version: 8.7.11.6 x64

Please see this issue I submitted to libjxl.  
[libjxl issue](https://github.com/libjxl/libjxl/issues/2105)

Essentially, ImageGlass is rendering a lossless jxl differently than the original jpeg.  Confirmed that two other viewers (Chrome & Imagemagick IMDisplay do not have the issue).

**Comment by d2phap** [comment]
Can you attach the image file? Thank you

**Comment by karoberts** [comment]
jpg
![jxltest](https://user-images.githubusercontent.com/7482126/214997329-eb07193e-ffbe-41e3-8619-25b2dc6614a4.jpg)
jxl (renamed to .jxl.jpg so github accepts it)
![jxltest jxl](https://user-images.githubusercontent.com/7482126/214997328-6acc95bd-f0e6-43ee-9ef0-340e7f94696d.jpg)

**Comment by d2phap** [comment]
This is because your JXL file contents an embedded color profile (SRGB). If you set Color profile (in Settings > Image > Color management) to None, ImageGlass will display exactly like the JPG file while the JPG file does not have the embedded color profile.

- The Imagemagick IMDisplay does not have color management feature.
- The output image of https://squoosh.app is as same as ImageGlass'.
- Irfanview with Color managemnent enabled also displays the JXL file as same as ImageGlass.

![image](https://user-images.githubusercontent.com/3154213/215261425-169a7498-860a-48dc-b20c-ba880d35b471.png)

**Comment by karoberts** [comment]
@d2phap Thanks, that's very helpful.  I wonder if it would make sense to default to "None" for those who might not be that color profile aware? (like me!)
