### ISSUE TITLE
Add 100% zoom breakpoint for mouse wheel

### ISSUE THREAD

**Issue by MapleRecall** [d2phap/ImageGlass#1507]
When zooming with mouse wheel, the scale goes right through 100%, e.g. 90% > 110%. Currently I have to use the menu or keyboard to view in 1:1. 

I think adding a breakpoint for 100% might be a good and easy way to get to pixel perfect quickly.

**Comment by SimonRene** [comment]
When I zoom using the mouse wheel the steps are ... 80 % > 90 % > 100 % > 125 % ... and backwards the same steps.
When does it skip the 100 % in your case?
Can you explain this issue in more detail?

**Comment by rxiv** [comment]
In Settings -> Image, you can already set the Zoom snap-to levels. Here are the default values in the Zoom Levels Box:

5;10;15;20;30;40;50;60;70;80;90;100;125;150;175;200;250;300;350;400;500;600;700;800;1000;1200;1500;1800;2100;2500;3000;3500

110 isn't on the list for the default options. Do you have 110 instead of 100?

**Comment by d2phap** [comment]
As others mentioned, you can customize the zoom levels in Settings > Image > Zoom levels.
