### ISSUE TITLE
Language resets to English after each update

### ISSUE THREAD

**Issue by iDm1** [d2phap/ImageGlass#1523]
### System information:
 - Windows OS version: 10
 - ImageGlass version:  8.8.3.28

### To Reproduce
1. Install older version (for example 8.7.11.6)
2. Select any language other than English
3. Update to newer version (for example 8.8.3.28)

### Actual behavior:
ImageGlass starts with English UI.

### Expected behavior:
Language setting should be preserver after update.

**Comment by d2phap** [comment]
I didn't realized this until checking the language pack file name. The suffix of each language pack file is changed according to the app version, so when the new update installed, it cannot find the old language file.

So I fixed in [v8.8.4.4](https://github.com/d2phap/ImageGlass/releases/tag/8.8.4.4) and it will take effect when user upgrade from v8.8.4.4 to later version.
