### ISSUE TITLE
WEBP images are distorted in 8.8.3.28

### ISSUE THREAD

**Issue by Balzhur** [d2phap/ImageGlass#1526]
### System information:
 - Windows OS version:  Win 11 x64
 - ImageGlass version:  8.8.3.28 x64, purchased at Windows Store

### To Reproduce
1. Open any WEBP image, zoom to 100%
2. Compare to the same image opened in Firefox, Chrome, Edge or any other image viewer

### Actual behavior:
Image opened in ImageGlass looks distorted.
I'm using "High-quality, bicubic" zoom optimization, switching optimization algorithms does not improve the situation.
Images are grainy and distorted. Situation is even worse with animated images.

### Expected behavior:
Image zoomed looks smooth and not grainy.

### Screenshots:
![image](https://user-images.githubusercontent.com/31563101/228768646-9feb342a-843b-42a4-babd-229dfcf44478.png)

### Additional context:
I suspect this is due to "directly using libwebp v1.3.0", previous ImageGlass version did not have this issue.

**Comment by Balzhur** [comment]
Samle image on screenshot taken from [here](https://file-examples.com/index.php/sample-images-download/sample-webp-download/) - 500KB version.

**Comment by Balzhur** [comment]
@d2phap, would you fix it in 8.x?

**Comment by d2phap** [comment]
It's fixed in `v9` branch and will be included in v9.0 beta 4. However, it requires a lot of work for v8 to do the same, so I added a fall-back feature that it will use MagickNET to load animated WEBP (as same as v8.7) if the `libwebp.dll` is not found.

It means, you will just delete `libwebp.dll` to use the animated WEBP function from v8.7. The new update will be released by 4/4.

**Comment by d2phap** [comment]
I released [v8.8.4.4](https://github.com/d2phap/ImageGlass/releases/tag/8.8.4.4) which you can just delete the `libwebp.dll` to use the MagickNET's animated WebP. ImageGlass 8.8 converts WebP frames to Gif format to use Gif animator, that's why it loses the quality.

It's totally fixed in v9.0 beta 4 which will be also released soon. WebP frames are directly rendered using the GPU without converting to Gif format, resulting in a significant performance boost.

**Comment by Balzhur** [comment]
Thank you. Workaround (deleting libwebp.dll) works as expected in 8.8.4.4. Non-animated WEBP images are also displayed properly.
As for 9.x beta branch - well, if you kindly fix the settings editing from the GUI, it would be usable, for now it's too much hassle to tinker with config file, at least for me.
