### ISSUE TITLE
Dimensions & Size Display, Txt file support, External Editors, Save as AVIF & WebP

### ISSUE THREAD

**Issue by norius-na** [d2phap/ImageGlass#1538]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

1. Dimensions & Size display.
2. Txt file viewing support.
3. Setting to specify 3-5 external editors.
4. Save as AVIF & WebP

### Describe alternatives you've considered

1. Dimensions & Size displays over the image, with option to disable. I think Dimensions & Size is basic to show.
2. Txt file viewing support. (Why text file? Some people keep there memos, ToDo list, song guitar chords in TXT file.)
3. Setting to specify 3-5 external editors. In IrfanView, user can edit settings.ini manually to add external editors with automatic hotkey support for each added editor. In real use, we use Paint, Paint.NET, Gimp, Photoshop, ... as CG editors. (And Notepad, Notepad+, EditPlus, Visual Studio Code, ... for TXT file if you support it)
4. Save as AVIF & WebP

**Comment by d2phap** [comment]
> Dimensions & Size

You can find it on the title bar. You can customize what info to show since v9.0 beta 1: https://github.com/d2phap/ImageGlass/issues/971#issuecomment-1133560019
![image](https://user-images.githubusercontent.com/3154213/232206900-9e9f2376-66ef-404e-91f7-4abe88a4fc67.png)


> Setting to specify 3-5 external editors. In IrfanView, user can edit settings.ini manually to add external editors with automatic hotkey support for each added editor.

You can add external editors as tools and assign hotkey for it in v9.0 beta 4. Please see [changelog of v9.0 beta 4, section "External tools support"](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416).

> Save as AVIF & WebP

v9.0 beta 4 supports saving as WebP format (including animation).

**Comment by Balzhur** [comment]
Txt file viewing support? What perversion is this? This is image viewer, not some notepad app.

**Comment by d2phap** [comment]
I close this because I have no plan for the rest.
