### ISSUE TITLE
NEF files appear darker with colors less saturated

### ISSUE THREAD

**Issue by donatopace** [d2phap/ImageGlass#1577]
### System information:
 - Windows OS version: Windows 10 Pro 64bit
 - ImageGlass version: IMAGEGLASS 9.0.4.416

### To Reproduce
Open picture ".nef" with  viewer:
"ImageMagick-7.1.1-10-Q16-HDRI-x64-dll.exe",
the picture shows similar to PHOTOSHOP viewer (OK),

but when opened with "IMAGEGLASS 9.0.4.416"
first the picture appear good and then darker with colors less saturated!

Problem is the same with all  .nef  files.
I have attached video in   .webm   and  picture.nef  in  .zip 

### Screenshots:
[Dark and colors  less saturated.webm](https://github.com/d2phap/ImageGlass/assets/43314459/21898499-0d40-4bd1-8c15-52b6b8085f17)

[Picture.zip](https://github.com/d2phap/ImageGlass/files/11558904/Picture.zip)

**Comment by d2phap** [comment]
Thanks for the sample file. I have just improved the color for v9.0. It's still slightly different from Photoshop (but it's the same as MS Photos), but I guess this is all I can do with MagickNET.

For v9.0, If you want to use the RAW embedded thumbnail only, you can set `UseEmbeddedThumbnailRawFormats` to `true`.
It's going to take some time to push a new release because I am in the middle of the work for v9.0 beta 5.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/34b09cb0-ce1e-4800-bcd8-576dedb8a738)

Anyway, thanks for your donation!

**Comment by donatopace** [comment]
In the right corner below of CAMERA RAW change Profile  from "Adobe Color" --> "sRGB"
and the color probably will look like similar, because "Adobe RGB"  is  a wide color Space(has more colors) while  "sRGB" is Small Color Space!

I will make others test
Thanks.
