### ISSUE TITLE
JNG image format support?

### ISSUE THREAD

**Issue by L2NE-dev** [d2phap/ImageGlass#1609]
Interesting about support of JNG image format support in future (in ImageGlass). I got support of such format by JS, uses a web-browser's native PNG (for alpha channel), JPEG decoders (by extraction), and HTML5 canvas (recently used color matrix filter for alpha channel, as fallback used a WebGL). What is JNG? It is JPEG Network Graphics, a MNG sub-format. If be shortly, it is JPEG with alpha channel (coded as PNG or JPEG grayscale).

**Comment by d2phap** [comment]
ImageGlass uses MagickNET (ImageMagick) library to decode the image file formats. It seems that ImageMagick [supports JNG](https://imagemagick.org/script/formats.php), if so, you can add `.jng` extension in Settings > File type associations so that ImageGlass will open it.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/97851563-a112-4f44-89d9-05478a8a6731)
