### ISSUE TITLE
"Save As" instead of "Save" after cropping.

### ISSUE THREAD

**Issue by laniakeadev** [d2phap/ImageGlass#1614]
### System information:
 - Windows 10
 - ImageGlass 8.8.4.4 and 8.8.6.9

### To Reproduce
1. Open an imae
2. Crop it
3. Click "Save" or "Enter"
4. 

### Actual behavior:
It shows up "Save As" menu and explorer, offers to save a copy.
Also if a save a file "Screenshot_droid.reader.book.epub.mobi.pdf.djvu.fb2.txt.azw.azw3.jpg", it saves as jpeg but without an extenstion: "Screenshot_2022-12-13-02-24-05-957_droid.reader.book.epub.mobi.pdf.djvu.fb2.txt.azw.azw3"

### Expected behavior:
Saves iimediately, replacing the original image

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/19239834/5b05d8b0-f18a-4fce-bbd2-ab6a6cdaba20)

**Comment by d2phap** [comment]
Since ImageGlass v8.8, the "Save" was changed.
- It only supports "Save" for the formats mentioned in the "Write" column here: https://imageglass.org/docs/supported-formats.
- For Cropping, the "Save" acts like "Save as".
This is to avoid the unexpected corruption issue which was reported many times here.

Fortunately, you can switch to v9.0 beta 5 (or at least beta 4), the corruption issue is fixed and the "Save" is restored to its original behaviour.

Also, this warning dialog will still show

![image](https://github.com/d2phap/ImageGlass/assets/3154213/f8284661-6e1d-4e32-8ed9-c78d34517056)
