### ISSUE TITLE
ThumbnailsCache folder bugs

### ISSUE THREAD

**Issue by thericle** [d2phap/ImageGlass#1647]
### System information:
 - Windows OS version: 11 Pro 22621.2215
 - ImageGlass version: 9.0.5.726

Related to this issue: https://github.com/d2phap/ImageGlass/issues/1292

It seems that the ThumbnailsCache folder empties when I re-open the program (even if I open the same Image as before).
Isn't the point of the ThumbnailsCache folder to keep a cache between runs, or am I wrong?
In case it matters, I have the gallery on the right side, and the thumbnail size set to 128 pixels.

Also, related to the above, the program doesn't seem to respect the "Maximum gallery cache size" setting, and there doesn't seem to be a way to completely disable thumbnail caching.

I'm sorry if any of the above is not due to a bug but my own lack of understanding.

**Comment by d2phap** [comment]
Thanks @thericle for reporting the issue! It should be fixed in [ImageGlass 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008)

To disable the cache, set "Maximum gallery cache size" to `0`, ImageGlass will still write cache to the folder in runtime, those cached files will be deleted after the app closes.
