### ISSUE TITLE
RC 9 Moon memory leak

### ISSUE THREAD

**Issue by Ainaemaet** [d2phap/ImageGlass#1676]
### System information:
 - Windows 11
 - ImageGlass version: 9.0 RC Moon

### To Reproduce
1. Open a gif in a long string of gifs (dozens, not sure if that has anything to do with it)
2. Open settings
3. Browse settings
4. Memory use in Windows skyrockets quickly to 99% and slows computer unless I can stop it first. 

### Actual behavior:
When opening a gif and browsing settings (I was trying to look for a way to slow the gif) memory use skyrockets and computer becomes unusable unless it is stopped.

### Expected behavior:
Open the gif, open settings and browse settings without memory leak occurring.

**Comment by d2phap** [comment]
- Can you attach the gif file?
- Does it happen to a specific file or all GIF files?

**Comment by d2phap** [comment]
I can reproduce the issue, but it causes by the menu. It's a known bug with .NET 8 (https://github.com/dotnet/runtime/issues/93520)

Steps to reproduce:
- Open ImageGlass 9 RC (.NET 8 build)
- Right-click to open context menu => no memory issue here
- Right-click to open context menu again => memory leak!

So it's confirmed they fixed in .NET 8 GA release: https://github.com/dotnet/runtime/issues/93520#issuecomment-1763167746.

**Comment by Ainaemaet** [comment]
Ok that's good to know. I was going to dig around so I could get a better
idea of what exactly was producing it, but you saved me the hassle ty. :)

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.7.1125](https://github.com/d2phap/ImageGlass/releases/tag/9.0.7.1125)
