### ISSUE TITLE
Windows Display Scale Factor not applied

### ISSUE THREAD

**Issue by janweigel** [d2phap/ImageGlass#1679]
### System information:
 - Windows OS version: 11 pro 22H2
 - ImageGlass version: 8.10.9.27 x64

### To Reproduce
1. Set the Windows Display Scale to any value other than 100% for example 200% on a hi-dpi screen
2. Open any image in Image Glass
3. Set the zoom to actual size

### Actual behavior:
The image zoom does not take the Windows scale factor into account. So on a display with hi-dpi and a scale factor of 200% set in the Windows display settings, the image is displayed as if the scale was set to 100%. So the actual displayed size on the screen is 50% of the size that is shown in other apps for example any browser like chrome, edge, etc.

### Expected behavior:
The displayed size of the image should take the Windows scale setting into account. Especially when the zoom is set to actual size. 
Or at least there should be an option to control the behavior.

**Comment by d2phap** [comment]
This is by design, photo viewer is different from a browser.

Browser applies DPI scale factor to the image, as a result, the image looks blurry and does not show the true dimension. 1000x1000 image on 200% DPI should be still displayed as 1000x1000.

I don't see any professional photo viewer/editor do this.
