### ISSUE TITLE
ImageGlass 9 is not installing as system wide application for all users.

### ISSUE THREAD

**Issue by krystofkrticka** [d2phap/ImageGlass#1708]
### System information:
 - Windows OS version: Windows 11 23H2 build 22631.2715
 - ImageGlass version: 9.0.7.1125

### To Reproduce
1. Install ImageGlass 9

### Actual behavior:

ImageGlass 9 is installing to user profile instead of program files.

### Expected behavior:

ImageGlass has option to be installed system wide.

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/37749100/69a239a3-6e9d-43e3-b0cf-c591cdf77f52)

### Additional context:

ImageGlass is being installed to user profile which is issue for me as system administrator because when I'm installing ImageGlass I usually want it to be available to all users of specific computer not just me as administrator in my profile. This is also kind of wastefull with storage without having an option to be installed system wide.

**Comment by d2phap** [comment]
As announced at https://imageglass.org/news/introducing-the-new-imageglass-version-9-88#breaking-changes, ImageGlass 9 switches to "Per-user setting" model.

To install IG 9 to all users, you just need to install it in `C:\Program Files\ImageGlass` folder. Click "Browse" button to select it.
![image](https://github.com/d2phap/ImageGlass/assets/3154213/2e3be1b0-80ce-4423-bffa-e295c36f6ff9)

**Comment by krystofkrticka** [comment]
@d2phap well technically this is not per user setting this is per user install, because take a look for example on everything it installs system wide but each user has option to have his own settings.

**Comment by d2phap** [comment]
- If your concern is about wasting storage resources because of "without having an option to be installed system wide", as I mentioned you can install in the "Program Files" folder so all users can use the app.
- Every user should have their own user setting file, this is the "Per-user setting" model of IG 9 (and many other apps).
- If you want to set the default user settings, you can create a `igconfig.default.json` file and deploy it to the "Program Files" folder, refer to https://imageglass.org/docs/app-configs for more details.

**Comment by asjimene** [comment]
Hello, the main issue with installing this application as a user-based application only is the ease of managing the software for large deployments. When switching to a user-based installation method, when doing device patching, the software needs to be patched for each user on the device. Additionally, when installing software using something like ConfigMgr or Intune, a per-user MSI would only install shortcuts for the user performing the installation, in these cases, that user is the SYSTEM account. On a shared device, that means that ImageGlass is "installed" but there are no shortcuts available to any of the users of the device.

I see that you are using Advanced Installer to package this application, is there a reason why you chose as "Per-user only" instead of "Per-machine if user is administrator, per-user otherwise"?

**Comment by krystofkrticka** [comment]
@asjimene Ah I see fellow sys admin colleague. Thank you, for your explanation because you did a better job then I did explaning this issue.

**Comment by d2phap** [comment]
I created a new build for MSI installer (unofficially):
https://drive.google.com/file/d/1m7YBMEyIjVLajxUvJdy6t_6SQAcfhLgl/view?usp=sharing, can you help to test?

User can choose between 2 options:
- Everybody: Default location is `C:\Program Files\ImageGlass`
- Only for me: Default location is `%LocalAppData%\Programs\ImageGlass\`

![image](https://github.com/d2phap/ImageGlass/assets/3154213/9c9db9f0-9c41-4ac1-9b7c-2955319e393c)

![image](https://github.com/d2phap/ImageGlass/assets/3154213/4f0bfbd3-bd33-4d78-a388-ffffa39f20b3)

The app still behaves the same:
- User config folder (contains `igconfig.json` and others) is located in `%LocalAppData%\ImageGlass`
- If you want to predefine the default settings, create `igconfig.default.json` in the installed folder
- If you want to lock some settings, create `igconfig.admin.json` in the installed folder

**Comment by xenadmin** [comment]
Does the MSI respond the the commandline switch `ALLUSERS=1` like it did in version 8?
I installed version 8 sucessfully like this on Citrix Terminalserver, all we need, is the same behavior:
`$UnattendedArgs = "/i $PackageName.$InstallerType ALLUSERS=1 /qn /norestart /liewa $LogApp"`
Ps.: Love the way how you handle lockdown settings, works very well on Citrix!

**Comment by d2phap** [comment]
@xenadmin honestly, I don't know much about MSI format, I just user the Advanced Installer UI to create MSI file. For the changes, see https://github.com/d2phap/ImageGlass/commit/e47e3dc790084824898ece48c05cecee9535d2d9

v8 msi code: https://github.com/d2phap/ImageGlass/blob/e47e3dc790084824898ece48c05cecee9535d2d9/Setup/v8/AdvancedInstaller/x64/ImageGlass-x64.aip

**Comment by Kill3r94** [comment]
Thank you for the update! I have tested the new MSI (9.0.7.1130) using the ALLUSERS=1 /qn flags (Running as SYSTEM) and confirmed that it both installs and updates without issues. Desktop and start menu shortcuts are all present on my test machine. Please let me know when that new installer has been officially released so we can update this in our catalog! Appreciate you quick response and support on this matter! 😊

**Comment by d2phap** [comment]
Published [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
