### ISSUE TITLE
Window on top and image blur

### ISSUE THREAD

**Issue by magickbird** [d2phap/ImageGlass#1736]
First of all I want to say that I sincerely love the app and been using it for a couple of years now, and it's great that you made a big update on it! But despite that fact the update changed a couple of things that mess with my regular workflow, these things are:

Keep window always on top was bind to the ` key, I really don't know what's the name of the key, but it's above the tab and on the left from the 1 on the keyboard. This feature was extremely helpful because if I need to pin or unpin images I can do it with just one button instead of extra mouse clicks, and my latest version of ImageGlass before the update had this bind. So I'm wondering if it's possible to return it?
Also on the sidenote I think there was an option to rebind anything you want in the app sometime ago, or is it just my memory messing with me?

Second thing that I have noticed after the updated is that some low res images like pixel art is now blurred when zoom is set to 100%, and it wasn't like this before, previously every pixel was really sharp at 100%, so if it's possible to change this thing or at least add some checkbox for it in the settings (I tried to find one but no luck)

**Comment by d2phap** [comment]
## 1
The hotkey for "Keep window always on top" is removed in v9 because a lot of people enable it accidentally. If you want to add it back in v9, follow these steps
- Open `igconfig.json` (go to Settings > General, click on `User setting file (igconfig.json)`)
- Exit all ImageGlass instances
- In `igconfig.json` file, add this to the `MenuHotkeys`:
```json
"MenuHotkeys": {
  "MnuToggleTopMost": ["`"]
},
```
- Save the file and open ImageGlass again

For more details about customizing the default menu hotkey, refer to https://github.com/d2phap/ImageGlass/discussions/1702#discussioncomment-7660806

## 2
For PNG blurry issue, refer here: https://github.com/d2phap/ImageGlass/issues/1716#issuecomment-1826406134
