### ISSUE TITLE
Ability to toggle full screen mode using mouse

### ISSUE THREAD

**Issue by AkibaWolf** [d2phap/ImageGlass#1753]
### Is your feature request related to a problem? Please describe.
The editor interface allows you to perform most operations using only the mouse. But to toggle full screen mode you have to use the keyboard.

### Describe the solution you'd like
My proposal is to assign middle mouse click to switch full screen mode as it is not used anywhere else in the application and is intuitive to use when you setup scroll to toggle between previous and next images.

**Comment by d2phap** [comment]
You can edit the `igconfig.json` file to customize the mouse click action ([originally supported since v9.0 beta 2](https://github.com/d2phap/ImageGlass/issues/991#issuecomment-1238130837)):

```diff
// in igconfig.json file
"MouseClickActions": {
  "WheelClick": {
    "ToggleOn": {
-     "Executable": "IG_Refresh",
+     "Executable": "MnuFullScreen",
      "Arguments": []
    }
  }
}
```

All supported mouse events:
https://github.com/d2phap/ImageGlass/blob/f26d16a6a35cede179a9b0656271ec4f8b63b009/Source/Components/ImageGlass.Base/Types/MouseEvent.cs#L26-L42

**Comment by vivadavid** [comment]
Hi,

I've also noticed that there's no way, as far as I know, to exit full screen with the mouse with just one click if you have previously enabled the option _Hide toolbar in Full Screen mode_.

If that's the case, first you need to right click somewhere on the image and then click on _Toolbar_. Second, you click on _Full screen_. To sum up, you need to click on two different buttons three times in total.

My suggestion would be to include an option in the settings, so that it can be customized. I'd go for double click by default. Manually editing the JSON file seems more complicated.

Thanks in advance!

**Comment by d2phap** [comment]
Setting UI for Hotkeys and Mouse click customization in my to-do list. But it's way more complicated to implement than directly editing in the json file.

**Comment by vivadavid** [comment]
Hi,

In that case, what about a little icon that could be displayed somewhere on the screen (for example, on the top middle part) when you are on full screen with the toolbar disabled? Pressing this icon would allow you to exit the full screen mode. It could be normally hidden and only displayed when you hover the mouse. I'm thinking about the way it works when you are on full screen on Chrome.
