### ISSUE TITLE
Support needed for new Nikon RAW image file compression formats called "High Efficiency" and "High Efficiency Star"

### ISSUE THREAD

**Issue by OldNikonShooter** [d2phap/ImageGlass#1812]
Hello. Nikon has released two new RAW image file compression formats with their latest flagship Nikon Z8 and Z9 cameras.  The formats are called "High Efficiency" and "High Efficiency Star".  But the problem: ImageGlass cannot properly decompress and display these new file compression formats (and all that can be seen is their small embedded image thumbnails).  This is true for all versions of ImageGlass I have used, including the latest version 9.0.9.1230.  I respectfully suggest adding to ImageGlass the ability to decompress & fully display images saved in both of these new RAW file compression formats.  Thank you for considering this!  Sincerely, GitHub member "OldNikonShooter"

**Comment by d2phap** [comment]
Hi @OldNikonShooter,
Do you have sample files for the formats? Since ImageGlass use MagickNET for decoding image formats, you should post your request there: https://github.com/dlemstra/Magick.NET/issues

But you can try adding the extension to ImageGlass if it can be opened:
- Open IG Settings, click tab File type associations
- Click "Add" button and enter the extension, example: `.jpg`
![image](https://github.com/d2phap/ImageGlass/assets/3154213/5c6088bd-1f8f-4886-9066-7edd0c0b1545)

**Comment by OldNikonShooter** [comment]
Hi @d2phap ,

Thank you for your reply and information. The file extension for these updated Nikon RAW files is still .NEF which is already associated in IG (and the older Nikon versions work fine within IG, meaning Magick.net supports them properly); thus, adding that extension is not a solution. What's new is Nikon's codec(s) used for the RAW contents within the .NEF container. So the solution is probably what you suggested: for me to post the feature request to Magick.net.  So I will post this feature request there.  Thank you!  Btw, I really enjoy IG; it is a fantastic program!  Thank you!

**Comment by d2phap** [comment]
Since this is upstream issue, I'm gonna close it
