### ISSUE TITLE
Add zoom and move capabilities in full-screen slideshow mode

### ISSUE THREAD

**Issue by i-iooi-i** [d2phap/ImageGlass#1879]
![image](https://github.com/d2phap/ImageGlass/assets/1827701/ae2518ad-1473-47f5-a5cf-72fe1a47c43e)

I really like the full-screen slideshow interface. 
I use it like this most of the time, it's simple, clean and cool!

But two important features are missing:
![动画1](https://github.com/d2phap/ImageGlass/assets/1827701/ecd3193c-6b4e-477f-b786-94af1de22c24)
When hiding the toolbar, you can hold down the border with the left mouse button to move the frame.

![动画1](https://github.com/d2phap/ImageGlass/assets/1827701/03e20203-25d7-4ad4-b1ac-37b0e5f9ae86)
Is it possible to increase the ability to drag the edges and corners to zoom the canvas in full-screen slideshow mode?

![动画1](https://github.com/d2phap/ImageGlass/assets/1827701/d277624b-cd25-46cb-8df6-56be6afba6b6)
It would look like this, it would be great.

**Comment by d2phap** [comment]
Hi @i-iooi-i 

You're talking about Frameless window mode, your requests already posted
- resizing window: #1330
- moving window: #1005, you can hold SHIFT key to move the window

Due to some limitations, I could not find a way to totally remove the window's border (frameless) and keep the native resize handlers
