### ISSUE TITLE
Unable to access version 9 after purchse

### ISSUE THREAD

**Issue by gds2817** [d2phap/ImageGlass#1910]
### System information
- Windows OS version: Win11 (64)
- ImageGlass version: 9
- ImageGlass release: Microsoft Store

### To Reproduce
1. Purchased 12/02/2023, Order Number: 2736673956
2. Getting error message and don't know how to proceed:
3. C:\ProgramFiIes\WindowsApps\9662DuongDieuPhap.ImageGIass_9,0.13.0 x 64_xjrmsr...ImageGIass,exe
4. CLip license device ID does not match the device ID in the bound device license.
5. 
6. 

### Screenshots / Video / Sample image file
![image](https://github.com/d2phap/ImageGlass/assets/169388382/802092fa-551c-4687-aee5-f98d230fa563)
![image](https://github.com/d2phap/ImageGlass/assets/169388382/ea670098-b845-45bc-b582-2bfe8592fadd)

**Comment by d2phap** [comment]
@gds2817 
This problem is from MS Store, you can try these links to check if it helps
- https://answers.microsoft.com/en-us/windows/forum/all/clip-license-id-does-not-match-the-device-in-the/516d78bc-5eb8-4670-8d57-a82b7a128a47
- https://www.reddit.com/r/techsupport/comments/wfp7r4/clip_license_device_id_does_not_match_the_device/
