### ISSUE TITLE
Not accepting scroll wheel input until window clicked

### ISSUE THREAD

**Issue by m00bus** [d2phap/ImageGlass#1980]
Specifically, this occurs on Win11 when the system setting "Scroll inactive windows when hovering over them" setting is DISABLED. ImageGlass accepts scrolls properly with the setting enabled, the scroll input is registered without first clicking the window. This workaround is particularly annoying when using Window Fit mode, as the constantly resizing window makes it difficult to keep the mouse cursor on top of the window to scroll - also, I typically leave the Windows "scroll inactive" setting disabled as it interferes with regular desktop usage, causing random scrolls on windows you happen to be hovering over instead of the active one.

My normal usage scenario is leaving IG on auto zoom + window fit, and setting the scroll wheel to navigate images rather than zoom, but the problem occurs when using the default scroll-to-zoom behavior as well.

Refocusing the ImageGlass window via other means eg alt-tab or clicking on the taskbar do not fix the scroll issue, the window must be clicked on. Both opening an image from Explorer and opening the program directly, then dragging an image in have the issue.

### System information
- Windows OS version: 11
- ImageGlass version: 9.1.8.723
- ImageGlass release: Classic

### To Reproduce
1. Disable Windows' "Scroll inactive windows when hovering over them" setting
2. Open an image with ImageGlass and attempt to use the scroll wheel
3. Click the windows and attempt to scroll again

**Comment by d2phap** [comment]
Hi @m00bus 

This is the expected behaviour. When you disable the system setting "Scroll inactive windows when hovering over them", Windows does not send the "scroll" message to the inactive window. As a result, ImageGlass does not receive this "scroll" message while being inactive, no scroll function activated. This applies to all apps, including the built-in apps, not only ImageGlass.

If you want to scroll the inactive window, simply just enable the setting.
