### ISSUE TITLE
WebView download fails during install

### ISSUE THREAD

**Issue by IrmaIsfot** [d2phap/ImageGlass#2029]
### System information
- Windows OS version: Windows Server 2022
- ImageGlass version: 9.1.8.723
- ImageGlass release: Classic

### To Reproduce
1. Run "ImageGlass_9.1.8.723_x64.msi" on a newly installed Windows Server 2022.

### Actual behavior
![ImageGlass fail on Windows Server 2022](https://github.com/user-attachments/assets/ab6b0aa5-637c-4f49-be12-89aea9d0e7e3)

### Expected behavior
I'm guessing the installer tries to help the user by downloading/installing the WebView runtime?

### Additional context
While the installer had paused with the time out message, I googled and installed the WebView runtime manually.
Then, when I clicked the OK button in the time out message, the installation proceeded and completed.

When starting the ImageGlass application, I got the .NET message telling me to install a newer .NET version.
![ImageGlass after install](https://github.com/user-attachments/assets/55eef33d-ed79-409d-a511-6e95b5844a3f)

Perhaps the WebView runtime can be handled in a similar way, if the specific Microsoft link (visible in the time out message) used in the installer is not persistent?

**Comment by d2phap** [comment]
Changes for running ImageGlass without WebView2 since [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104)
- WebView2 Runtime is now optional
- Without WebView2 Runtime:
  + A warning popup appears when opening "Quick Setup" showing the unavailable features and including download link
  + Opening Settings directly opens `igconfig.json` file with the associated app, or Notepad
  + Accessing the About dialog, Check for Update dialog shows the native Task Dialog
  + Viewing SVG format switches back to the native renderer

![image](https://github.com/user-attachments/assets/8af1659c-9ba2-4d71-b632-21bfbd6473be)

**Comment by IrmaIsfot** [comment]
Nice!
If there is a persistent link to where WebView2 can be downloaded from, or some kind of "start-page" for WabView2 info, then maybe you can link to that from those "Please install WebView2..." messages?
