### ISSUE TITLE
Image rotation is not lossless

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#219]
Hello! I recently started using ImageGlass instead of IrfanView because your program doesn't crash when loading files from our network server.

I made a frightening discovery that  hope you will address. Rotating a photo in your program automatically overwrites the original - this is unexpected and dangerous, as the rotation is not lossless (the file sizes dropped to a quarter of what they used to be)!

We're now having to restore several important photographs from our backups... if this feature provided truly lossless jpg rotation instead, it would be both safe and very useful.

Thanks for all your hard work on this program!  :)

-Eric F. Keebler.

**Comment by d2phap** [comment]
I will disable this auto-saving feature if rotation in the next release until the lossless saving is implemented.

**Comment by monkeynoises** [comment]
If someone does a rotate, then moves on to the next image...then please show a "do you want to save the rotated image?" yes/no.....if they move onto the next image.

I use ImageGlass to rotate and rename images....so I need a quick way to rotate and save. With the disabling of the auto save on rotate, one now has to remember to explicitly do a Save before moving onto the next image, otherwise the rotation is lost/not applied - it makes the process a bit clunkier than before.
