### ISSUE TITLE
Suggestion: DDS support

### ISSUE THREAD

**Issue by KyoGrou** [d2phap/ImageGlass#251]
Since my work use the .DDS extension a lot, it would be nice if the app can support this, so I won't have to use another specific app to open this extension.

I also added the .DDS icon, as mentioned in: https://github.com/d2phap/ImageGlass/issues/217

**Comment by d2phap** [comment]
You can open DDS file by adding new extension to ImageGlass
- Go to `Settings` > `File Associations` tab
- Click Add button then key in `.dds` extension
- Click `OK` to apply your change.
- Enjoy!

![image](https://user-images.githubusercontent.com/3154213/31951322-54aa46da-b910-11e7-8264-7cfe990782ad.png)

**Comment by lobotomy-x** [comment]
hello reopening this old issue to see if you'd consider adding support for alpha channel packed DDS. Here is an example of a texture file that packs glow/emission info in the alpha channel 
![image](https://github.com/d2phap/ImageGlass/assets/10409982/5337973a-bfee-4862-a846-e44f3309c88e)
and here's the alpha channel
![image](https://github.com/d2phap/ImageGlass/assets/10409982/2174a542-25e8-4729-93c9-0534d319276a)
The alpha channel is mostly black so when loaded as transparency we get this
![image](https://github.com/d2phap/ImageGlass/assets/10409982/35fdb601-ff48-42e6-8e3c-9f137efa184e)

I can see that imageglass does in fact support multiple channels but its unable to load them properly from DDS. This is not high priority to me because there are other tools for handling DDS but there really isn't a quick viewer as I have to load them into photoshop to see the correct view. Since the feature is almost there it would be nice to complete it and I thought it would be good to inform you of the issue although I'm not expecting any immediate fix 

![image](https://github.com/d2phap/ImageGlass/assets/10409982/de45de1e-dd54-4e7d-ada0-313797f17697)
