### ISSUE TITLE
add PDF support (read only) please

### ISSUE THREAD

**Issue by trollworkout** [d2phap/ImageGlass#280]

**Comment by d2phap** [comment]
Hi @trollworkout 

You can install Ghostscript (not for commerce use) for PDF support:
https://www.ghostscript.com/download/gsdnld.html

However, ImageGlass just can open the first page of PDF file. 
There is no plan for full PDF file support yet because I think it's easy to throw the pdf file to browser and view it :)

**Comment by smaragdus** [comment]
For me ImageGlass is an image viewer and support for non-graphic files would mean one thing- bloat. This has happened recently with [FastStone Image Viewer](http://www.faststone.org/FSViewerDetail.htm) which now can play video files and thus it is betraying its purpose- viewing of image files. I do not like this- there is an overabundance of video players which handle video formats better. So for me support for PDF would be meaningless and unreasonable and would not make ImageGlass a better image viewer.

**Comment by d2phap** [comment]
Agree with @smaragdus 
ImageGlass is a simple modern image viewer. To keep it fast and simple, I don't want to add too many things inside (actually now it's getting fat). 
For advance user, there are more options to go with :)

**Comment by trollworkout** [comment]
well im not using this program then good day
