### ISSUE TITLE
Can't use right arrow to go to an older image

### ISSUE THREAD

**Issue by madprops** [d2phap/ImageGlass#308]
### Expected behavior:
I'm used to use right arrow to go to older image, and left arrow to go to newer image, since that's how they are ordered in the file explorer.

### Actual behavior:
Does the opposite. Couldn't find an option to change that.

### Steps to reproduce:
1. Open an image in a directory with multiple images
2. Use the arrow keys

### System info:
- ImageGlass version: 4.1.7.26
Windows 10

### Other info:
Sorry if this is no longer relevant. But I tried to find a configuration for it and couldn't find it. Also I might be using an older version.

**Comment by d2phap** [comment]
Hi @madprops 

The `right arrow` will navigate the next image, `left arrow` will do opposite. 
It depends on the loading order of images. You can change it in Settings > Image > Image loading order

But there is no option to make `right arrow` navigates back and I won't implement because it breaks user experience
