### ISSUE TITLE
File real-time update in the viewing directory

### ISSUE THREAD

**Issue by AlexBlandin** [d2phap/ImageGlass#316]
Back in 4.1 ImageGlass would update alongside the contents of a directory, allowing me to see images that streamed into the directory (as a result of batch processing etc.) but would always get confused on which image it was displaying when new images come before it (it would not change which image it's displaying, but it would also not update to that image's position in the list, e.g. ImageGlass displaying image 5/32 updates to "displaying" image 5/33 when a new image is added to the directory, when the image it's *actually* displaying is 6/33, so moving right would just display the same image).

4.5 just doesn't seem to update alongside the directory, which is at least more stable for just viewing each image, but more annoying for going to the newer ones.

Can we make auto-updating with the directory a feature again, but with better stability such that it will still display the same image and moving left/right moves to the previous/next of wherever that image is *now*, rather than the previous/next of wherever the image previously was?

**Comment by d2phap** [comment]
Hi @AlexBlandin 

As there was some issues with real-time update image on v4.1 (detect **new** images; detect **deleted** images; detect **modified** images), the real-time update algorithm was changed since v4.5. I think it is more stable than v4.1, there is still an issue with detecting deleted images though (#270, #296).

I also tested your issue with a single file and multiple files, and it worked well.
The behavior as below:
- Detect new image
- Append the new image to the list, not follow list order.
- Update the number of images when user view other image

![iig](https://user-images.githubusercontent.com/3154213/38073955-b7c68eda-335f-11e8-84e0-f5bd467997d6.gif)

Anyone is facing the same issue?

**Comment by d2phap** [comment]
I just realized the **case sensitive**: `PNG` vs `png`.
Only all lower case extensions are triggered.
I also push a commit to fix it. It may also fix a lot of related issues: #309 #296 #288 #270 #316 #193 

You can try the latest build here: http://www.imageglass.org/moon
