### ISSUE TITLE
A few SUGGESTIONS for ImageGlass to make this amazing product Absolutely Best..!

### ISSUE THREAD

**Issue by mystarsare** [d2phap/ImageGlass#342]
Imageglass 5.0.5.7

1. software generally takes a bit long time to open compared to other viewers. Can you make it a bit faster?

2. people love that Window less look of Picasa image viewer (floating, with transparency), & it was BLAZING FAST. Can you have a settings option for such view (you can also have option to show thumbnail bar in that view).
see this preview of picasa viewer..
![jaq8z](https://user-images.githubusercontent.com/39171013/39949569-221781e4-5599-11e8-8ce0-8a62634d3d47.jpg)

3. it would be nice if you provide some more image editing options (like xn viewer)

4. we love your clean & neat ui, are you planning for any such video player in future..?

5. if we want to browse through images very fast, & we keep on pressing Left/right keyboard button continuously, it goes to only 1 image previous/next. actually it should scroll through images very fast if we continuously press a button.

6. option to view image file's properties (Deep & detailed informations)

7. support for HEIC images..!!

8. inbuilt theme editor (so that we can easily make & use our own themes)

9. hide everything else on the screen (like icons, menu button, thumbnail, etc.) when we open an image. make them visible for a brief period if we move mouse/press any key ..& then again disappear. it gives an immersive view of the photo..

{  QuickPic image viewer is an amazing android image viewer. you can take some inspiration from that too..!!  } 

{  Can u tell us 'When will v 5.0.5.11 be available as stable version (not moon/beta)..??'  }

**Comment by d2phap** [comment]
> 1. software generally takes a bit long time to open compared to other viewers. Can you make it a bit faster?

As I mentioned #341, _The more files there are, the slower ImageGlass loads_. It can be improved.


> 2. people love that Window less look of Picasa image viewer (floating, with transparency), & it was BLAZING FAST. Can you have a settings option for such view (you can also have option to show thumbnail bar in that view).

You can hide toolbar, thumbnail bar of ImageGlass as well. The UI improvement will be considered if it doesn't impact to overall performance. Since the app is written by C# Winform, it's tough to customize the UI.


> 3. it would be nice if you provide some more image editing options (like xn viewer)

ImageGlass is a simple image viewer, people can integrate other editing app via ***Edit Image*** menu.


> 4. we love your clean & neat ui, are you planning for any such video player in future..?

Thanks but no plan yet 😆 


> 5. if we want to browse through images very fast, & we keep on pressing Left/right keyboard button continuously, it goes to only 1 image previous/next. actually it should scroll through images very fast if we continuously press a button.

We provide ***Go To*** function and some shortcuts: `End`, `Home` to help people browse images. Adding "keep on pressing" makes ImageGlass laggy (as of now).


> 6. option to view image file's properties (Deep & detailed informations)

Refer to #336 

> 7. support for HEIC images..!!

You already can open HEIC images (non-animated only) with ImageGlass 5.0.5.11 😄 


> 8. inbuilt theme editor (so that we can easily make & use our own themes)

Theme editor is temporarily disabled in v5.0.
You can manually create theme by change `*.igtheme` to `*.zip` file, unzip it, and edit `config.xml` file

> 9. hide everything else on the screen (like icons, menu button, thumbnail, etc.) when we open an image. make them visible for a brief period if we move mouse/press any key ..& then again disappear. it gives an immersive view of the photo..

You just can toggle visibility of toolbar, thumbnail bar. 
Some people don't like the viewer that has too many things covering their viewing image. Hence, I just make it simple!

> 10. When will v 5.0.5.11 be available as stable version (not moon/beta)

If the build is stable enough for official release, it will push it. Normally it takes a week.

-------

Close this because the answers are clear.
