### ISSUE TITLE
Winrar 

### ISSUE THREAD

**Issue by mymain69** [d2phap/ImageGlass#35]
I downloaded a few pictures and found that if I open the pictures from winrar so something like this
http://i.imgur.com/NBk0lUt.png, by closing winrar before imageglass has a chance to load it that imageglass doesn't load the picture. Please fix thank you Dương

**Comment by d2phap** [comment]
Hi @mymain69 
This caused by WinRar. Once you directly open a file in WinRar without extracting, it will be extracted in a temporary folder. After closing WinRar, it will be deleted as default. ImageGlass is equipped real-time file's existence detection feature and it closes viewing picture immediately because this one becomes unreal file.
