### ISSUE TITLE
Scale window to actual image size, until fill, on open

### ISSUE THREAD

**Issue by SLinxTheFox** [d2phap/ImageGlass#451]
So i just got this program after using nexus image viewer, and it does just about everything i wanted it to do that nexus does and doesn't do; however, there is one thing that i found very useful that nexus could do that image glass cannot.

Nexus had a setting where any picture you opened would open as the actual size (as if you hit ctrl+m in image glass), but if it was larger than the screen could fit it would just fill. I would very much like that as it lets me know if i can use it for backgrounds aswell as if it's a decent resolution in general.

It would also be nice to have zooming in and out increase or decrease the window size, have an option where the window size always = the image borders

**Comment by fire-eggs** [comment]
> Nexus had a setting where any picture you opened would open as the actual size (as if you hit ctrl+m in image glass), but if it was larger than the screen could fit it would just fill.

I'm pretty sure the closest offering in ImageGlass is the setting "auto-zoom" (CTRL+A). When on, if the image is larger than the IG window, it will fill the window; if the image is smaller than the IG window, the image will be shown at 100%.

But because you reference "CTRL+M", i.e. make the IG window the same size as the image, I read your request as a mode where: "ImageGlass automatically changes its window size to fit the image, unless the image is larger than the screen, when the ImageGlass window is made as large as possible".

Please let me know if I have misunderstood.

> have an option where the window size always = the image borders
This might be accomplished by having the "Lock Zoom Ratio" feature also apply to "CTRL+M", which it currently does not.

**Comment by SLinxTheFox** [comment]
yeah your summary is right, that's what i'd very much like. especially as a default, not something i have to press a hotkey every time i open a new image. 

The ctrl+m is close because i have a 1440p monitor and most of what i look at isn't larger, but any photos or high res art i look at will go off screen. so having to press that with every new image AND having it not always turn out well irks me a bit, but other  than that i really like this program. Nexus couldn't show anything with 24 bit depth and had less universal settings like image order. it would be nigh perfect with this feature and the zoom one i mentioned at the end

**Comment by Hoowah** [comment]
If you like the idea of starting options, it may be best to handle this request with [#438](https://github.com/d2phap/ImageGlass/issues/438) 

Specifically a starting scaling mode and window size mode

> This might be accomplished by having the "Lock Zoom Ratio" feature also apply to "CTRL+M", which it currently does not.

Lock Zoom Ratio would make Ctrl+M persistent when navigating through images right? You probably don't want that because the window size will change when browsing, along with the location of the previous/next buttons. Changing window sizes would also make the thumbnail gallery practically unusable. 

Without major redesigns to interface/navigation, you'd only want this window scaling behavior to be applied when starting a new instance.

**Comment by eckso** [comment]
I suscribe to this feature, I only want to see the image, no toolbars, gallery, etc just the image and navigate with the keyboard arrows or ImageGlass navigation arrows.

Actually a borderless mode would be cool, to test press Alt + Enter to go to fullscreen, then Ctr + M to adjust the window size to image. Looks sick.

**Comment by SylwesterZarebski** [comment]
I think it is duplicate to the same (mine) issue #393 besides of borderless mode, which would be even cooler ;-).

**Comment by SLinxTheFox** [comment]
> I think it is duplicate to the same (mine) issue #393 besides of borderless mode, which would be even cooler ;-).

oh yeah, it is. and I would still totally love this as a feature

**Comment by d2phap** [comment]
Hey, here you go!

- Implemented in the new window mode, called: `Window fit (F9)` (its former name is Adapt window to image - `Ctrl+M`).
- User can combine with `Frameless (F10)` mode to make it cooler!
- More details of all window modes in ImageGlass and its combinations: #655 

Try the latest build: https://imageglass.org/moon
Feedback are most welcome!

**Comment by SLinxTheFox** [comment]
> Hey, here you go!
> 
> * Implemented in the new window mode, called: `Window fit (F9)` (its former name is Adapt window to image - `Ctrl+M`).
> * User can combine with `Frameless (F10)` mode to make it cooler!
> * More details of all window modes in ImageGlass and its combinations: #655
> 
> Try the latest build: https://imageglass.org/moon
> Feedback are most welcome!

I actually couldn't love imageglass more now. It's everything I've wanted in an image viewer now. thanks so much!
