### ISSUE TITLE
Fatal issue prevent ImageGlass from launching

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#469]
Hi,
I want to say I'm truly sorry because most my posts bugs and issues, I wish it was different.

Actually, I had noticed this issue for a while, but it didn't bother me since I know what it wrong and the workaround.
But now it really will be a serious issue for most users, especially the new ones, and we should always care about the users.

**Issue:**
If `ImageGlass folder` doesn't exist in `C:\Users\UserName\AppData\Roaming\` ImageGlass won't opening
It means any new user will try ImageGlass moon last ver, will get this fatal issue (cause this folder doesn't exist and ImageGlass failed to write it).

Navigate to `C:\Users\UserName\AppData\Roaming\` and try to rename `ImageGlass` to e.g. `-ImageGlass ` or delete it.
After that try to open ImageGlass moon last ver (won't open).

ImageGlass portable ver, not really completely portable.
The portable version it should read and write from its directory, but still write `igconfig.xml` file to `C:\Users\UserName\AppData\Roaming\ImageGlass` and
I think it's unnecessary because its already write and read  `igconfig.xml` from its directory.

Thanks!

**Comment by AnotherDimension-Ex** [comment]
Another completely weird issue have related to the screen.

I figure sharing this issue just in case if someone wondering why there's something wrong with the UI in the setting?

This issue only on some screens but not on High DPI screens.
Probably this VS fault.

**Suggestion:** for the `toolbar` buttons (using Unicode symbols with Arial font or svg images).
⮜ ⮝ ⮞ ⮟

**Suggestion:** for `Open File Associations`
Changing the height & width

<br>

**HD screen**
<p><img height=100" src="https://user-images.githubusercontent.com/34074375/50179805-0dacb980-0319-11e9-94f6-46b52b581287.jpg" ><img width="10" />
<img height=100" src="https://user-images.githubusercontent.com/34074375/50179806-0dacb980-0319-11e9-958d-cf321595da54.png" >
</p>

**High DPI screen**
<p><img height=100" src="https://user-images.githubusercontent.com/34074375/50180413-94ae6180-031a-11e9-8c0e-ee274f1a49e0.png" ><img width="10" />
<img height=100" src="https://user-images.githubusercontent.com/34074375/50180418-9aa44280-031a-11e9-80fa-157aa1dd30e8.jpg" >
</p>

**Comment by d2phap** [comment]
Hi @AnotherDimension-Ex 

Really appreciate your report for this issue because ImageGlass Moon is still under testing. 
This is how Portable mode enabled:
- On startup, IG will check if the startup folder is writable.
- If yes, IG will enable `Portable` mode, the `ConfigDir` is the startup folder.
- If no, IG will enable `Installer` mode, the `ConfigDir` is `%appdata%\ImageGlass`. 

Since ImageGlass Moon 5.5.x, **IG has no long used Registry** to store app settings, but `igconfig.xml` file instead. This file and the others (`Themes`, `Languages`, `igstartup.profile`, ...) are store in a relative folder called `ConfigDir`. This `ConfigDir` path depends on the startup mode of IG (Portable / Installer).

This change is more convenient for the users to just copy ImageGlass folder to run portable mode without breaking Theme, Language.

And for this `Fatal issue prevent ImageGlass from launching` issue, I forgot to create `%appdata%\ImageGlass` folder if it doesn't exist.

----------

About the UI issues, I will make change accordingly.

Thanks again!

**Comment by d2phap** [comment]
Fixed the issue, updated IG Moon v5.5.12.19
