### ISSUE TITLE
When opening certain images (maybe due to image size? file size?) the mouse arrow stays as the loading circle

### ISSUE THREAD

**Issue by Stealth3** [d2phap/ImageGlass#485]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/d2phap/ImageGlass/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9E+bug%22) and [closed](https://github.com/d2phap/ImageGlass/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22%F0%9F%90%9E+bug%22+) issues to ensure it has not already been reported

### System information:
 - Windows OS version:  Win10
 - ImageGlass version: 6.0.12.29

### To Reproduce
1. Open an image

### Actual behavior:
Most images load fine
Certain images (not sure what the criteria is) load fine but the mouse cursor stays as the loading circle

### Expected behavior:
Cursor should revert back to pointer when image loads

### Screenshots:
I tried adding a screen shot but even using the print screen button doesn't include my mouse cursor in a screen shot :(

**Comment by AnotherDimension-Ex** [comment]
Yes, you are right, I noticed this also with some heavy images.
I think this because when the app is loading image data will be busy and change the cursor, and for some reason still busy even after load image data.
```
picMain.Cursor = _isAppBusy ? Cursors.WaitCursor : Cursors.Default;
```
I think using "Cursors. WaitCursor" is needless, and at less for me it still busy a lot of times with no reason.
<br>

Also, the loading message, it became annoying, because when navigate, fast with some heavy images, it still displays after the image loading for a long time (e.g. 10-20 Sec).
Because the timer is set for 2 Sec, and when skip for example 10 images with loading message.
The result 2 x 10 = 20 Sec, 
Because the time still "Tick" from skipped image (only when navigate faster).
That's what it looks like for me, and I could be wrong.

I would request an option to disable the loading message.
An option in the setting would be nice.

**Comment by AnotherDimension-Ex** [comment]
Yes, you are right, I noticed this also with some heavy images.
I think this because when the app is loading image data will be busy and change the cursor, and for some reason still busy even after load image data.
```
picMain.Cursor = _isAppBusy ? Cursors.WaitCursor : Cursors.Default;
```
I think using "Cursors. WaitCursor" is needless, and at less for me it still busy a lot of times with no reason.
<br>

Also, the loading message, it became annoying, because when navigate, fast with some heavy images, it still displays after the image loading for a long time (e.g. 10-20 Sec).
Because the timer is set for 2 Sec, and when skip for example 10 images with loading message.
The result 2 x 10 = 20 Sec, 
Because the time still "Tick" from skipped image (only when navigate faster).
That's what it looks like for me, and I could be wrong.

I would request an option to disable the loading message.
An option in the setting would be nice.

**Comment by AnotherDimension-Ex** [comment]
Yes, you are right, I noticed this also with some heavy images.
I think this because when the app is loading image data will be busy and change the cursor, and for some reason still busy even after load image data.
```
picMain.Cursor = _isAppBusy ? Cursors.WaitCursor : Cursors.Default;
```
I think using "Cursors. WaitCursor" is needless, and at less for me it still busy a lot of times with no reason.
<br>

Also, the loading message, it became annoying, because when navigate, fast with some heavy images, it still displays after the image loading for a long time (e.g. 10-20 Sec).
Because the timer is set for 2 Sec, and when skip for example 10 images with loading message.
The result 2 x 10 = 20 Sec, 
Because the time still "Tick" from skipped image (only when navigate fast).
That's what it looks like for me, and I could be wrong.

I would request an option to disable the loading message.
An option in the setting would be nice.

**Comment by fire-eggs** [comment]
OK, I've seen this myself, I'll dig into it further.

**Comment by fire-eggs** [comment]
I've identified both a problem and a possible race condition with the 'Loading' message and busy cursor display. I'll be testing my changes to see if the problem continues.

The 'Loading' message is only supposed to appear if loading a given image takes longer than 2 seconds.
I can understand the desire to turn it off if it gets 'stuck'.

**Comment by d2phap** [comment]
Uploaded IG Moon 6.1
https://imageglass.org/moon
