### ISSUE TITLE
Zoom lock does not lock image position as well

### ISSUE THREAD

**Issue by aeon3** [d2phap/ImageGlass#486]
There's this issue with zoom lock that happens when, for instance, I have a couple of similar images and I zoom into them AND move them away from their neutral position. The zoom locks but when I go forward on to the following image, it resets the position of the first one, which defeats the purpose of the zoom lock for comparing pictures.
I am not sure if it's a bug or intended but in any case we should probably have an option for "location lock"   as well.

Thanks!

**Comment by AnotherDimension-Ex** [comment]
I also support this request highly.

Because zoom lock ratio it locks image zoom based on the center.

**I think what IG can do, is to add new options.**
1. Remember zoom and position if the next/prev image is exactly the same resolution.
2. Remember zoom for each separated image like "Picasa".
3. Remember zoom and position for all images (as possible).

I really want **option 1** more than the others, because when I edit an image I want to see the difference (before and after) for just the exactly the same next/prev image.
But not for different Images.

_Thanks!_

**Comment by aeon3** [comment]
> I also support this request highly.
> 
> Because zoom lock ratio it locks image zoom based on the center.
> 
> **I think what IG can do, is to add new options.**
> 
> 1. Remember zoom and position if the next/prev image is exactly the same resolution.
> 2. Remember zoom for each separated image like "Picasa".
> 3. Remember zoom and position for all images (as possible).
> 
> I really want **option 1** more than the others, because when I edit an image I want to see the difference (before and after) for just the exactly the same next/prev image.
> But not for different Images.
> 
> _Thanks!_

Exactly!

**Comment by d2phap** [comment]
Thanks!
The `Lock Zoom ratio` is just lock the zoom ratio, not included position.
I marked this as improvement to do in the future

**Comment by d2phap** [comment]
Close and merge to #795
