### ISSUE TITLE
Display picture title in thumbnail bar

### ISSUE THREAD

**Issue by caijibdn** [d2phap/ImageGlass#539]
Add an option， allow Display picture title in thumbnail bar

**Comment by d2phap** [comment]
This issue is implemented in the ImageGlass Moon v9.0 beta 1: https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514.
You can change `ShowThumbnailFilename` to `true` in the `igconfig.json` file.

![image](https://user-images.githubusercontent.com/3154213/169642127-78ada6d2-b42d-406d-b141-d28adda07d17.png)
