### ISSUE TITLE
Disable Alpha channel while keeping RGB (or combo) channels enabled.

### ISSUE THREAD

**Issue by Polylemongon** [d2phap/ImageGlass#593]
### Currently you can only view channels separately or ALL at once.

I work with many textures for my game development work and need to view them in a great image viewer program, love ImageGlass for this, however some old game textures I'm working with use alpha channels as their specular and cannot view them properly in ImageGlass with the alpha channel being enabled all times (Since "ALL" button enables everything). It would be awesome if we could view textures with RGB on (or any combination of RGB channels) but alpha disabled. Could we be able to combine on/off view states for channels in the current menu to solve this issue?.

Cheers!

**Comment by d2phap** [comment]
@Polylemongon 
Thanks for the suggestion, can you send me the sample files and some screenshots of the expectation?

**Comment by Polylemongon** [comment]
@d2phap 
This isn't necessarily the old textures fault, this overall any game texture that has an alpha channel. 

In this .zip you will find original .tga textures (old game texture and a new game texture) as well as screenshots on how they look currently in IG and a mockup of how we should see textures by just disabling alpha only and keeping RGB enabled or any combination.

[Images.zip](https://github.com/d2phap/ImageGlass/files/3449768/Images.zip)

**Comment by fire-eggs** [comment]
Now that we're making a trial of more than one floating tool window, I think this is another good candidate. The existing menu based system is a little awkward, even when cycling channels for a single image.

Something like:
![image](https://user-images.githubusercontent.com/9809727/64181901-4eac1600-ce35-11e9-827b-885f792b8885.png)
The "all" checkbox could be a toggle between All/None to quickly set or clear all channels.

Benefits:
- User can choose one _or_more_ channels to view
- View channel 'state' is obvious [I got weirded out at one point because I inadvertently left the view channel menu to 'red' and wondered why all my images looked grey!]
- Easier to use?

**Comment by bitsycore** [comment]
Hey, this feature would be really usefull for me too, for gamedev but also 3D art in general.

If doing that menu like proposed by fire-eggs is too complexe, just an option to disable alpha computation on color channel could be handy, because when I see a color channel I don't except alpha to be applied to it.

Thanks

**Comment by Unordinal** [comment]
This would be an extremely nice feature to have - I work a lot with packed textures that store roughness and other such things in their alpha channels which requires me to have a separate image viewing program solely to be able to properly see them.

A toggle in the settings menu to disable viewing the alpha when viewing just one of the RGB channels would work great for this purpose too, albeit less flexible than the checkbox idea.

**Comment by festivities** [comment]
I second this, channel packed textures are unfortunately interpreted wrongly in both IrfanView and ImageGlass, and I don't see any other alternatives other than just loading it in an actual image manipulation program like Photoshop.

**Comment by d2phap** [comment]
This feature is supported in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529).
You can toggle the RGBA channels separately via the context menu or Main Menu > Image > View channels.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/77f625e2-164d-4c59-85f5-c312c5b24970)
