### ISSUE TITLE
Make title bar themeable

### ISSUE THREAD

**Issue by marnick-s** [d2phap/ImageGlass#595]
I dont know if this is possible, but it would be a nice feature if you could add the option to give the Windows toolbar a color that matches the background of the installed ImageGlass theme.

With the toolbar I mean this: https://i.imgur.com/fbCryTH.png

![image](https://user-images.githubusercontent.com/3154213/66095069-c3a37480-e5c8-11e9-96c3-868424dacd84.png)

**Comment by kid1412621** [comment]
and stick image to desktop fixed

**Comment by d2phap** [comment]
Hi @kid1412621 
What do you mean about "and stick image to desktop fixed" ?
Thanks

**Comment by kid1412621** [comment]
@d2phap 
my bad, I mean, a feature allows user to pin images to desktop(above wallpaper, or even other windows) like a sticker without titlebar. And free to drag around. It will be greatly helpful for some cheat-sheets or memos.

**Comment by d2phap** [comment]
@kid1412621 
Since IG Moon support `Frameless` and `Window fit` mode, you can do it with the `Keep window always on top` option. https://imageglass.org/moon

**Comment by kid1412621** [comment]
@d2phap cool, just checked it out. That's exactly what I'm looking for! And two more requests: ability to  freeze the window and drag freely.

**Comment by d2phap** [comment]
@kid1412621 


> ability to freeze the window(in order to prevent from pressing ESC accidentally )

You can uncheck the option:
![image](https://user-images.githubusercontent.com/3154213/70997237-881c3f00-210f-11ea-986f-a6504f95eae0.png)



> lock the ratio when adjusting the window size.

The zoom modes: `scale to fit` / `scale to fill` / `lock zoom ratio` may fit you
![image](https://user-images.githubusercontent.com/3154213/70997416-05e04a80-2110-11ea-87a0-d7b7e03dfcf1.png)

**Comment by kid1412621** [comment]
@d2phap u r soooo kind, thx. 
But there is a little different from what I want.
I want to disable `ESC` only in the frameless mode.
And I mean lock the ratio of the window, not the picture. Just in case this situation happens
![image](https://user-images.githubusercontent.com/26278054/71002735-dedb4600-211a-11ea-9e50-a4de5a43f7f2.png)
Wanna window size fit image perfectly, currently those options cannot solve this.

**Comment by fire-eggs** [comment]
Moved @kid1412621 's hijacking feature requests to a new issue.

**Comment by Unknow0059** [comment]
Ever since Windows 8.1 users have been able to change the color of the title bar, and on Windows 10 this is the procedure: 
![image](https://user-images.githubusercontent.com/25656892/85922058-f710e800-b856-11ea-8a60-9d5335fd14fc.png)

**Comment by Unknow0059** [comment]
Ever since Windows 8.1 users have been able to change the color of the title bar, and on Windows 10 this is the procedure:
![image](https://user-images.githubusercontent.com/25656892/85922147-77cfe400-b857-11ea-80d7-92787b0ec1f2.png)

**Comment by d2phap** [comment]
IG uses native Windows title bar, you can just change its color as @Unknow0059 mentioned.
I want to keep IG simple so I will not implement this.

**Comment by DarkotHub** [comment]
> IG uses native Windows title bar, you can just change its color as @Unknow0059 mentioned. I want to keep IG simple so I will not implement this.

This is not a very reasonable solution as far as the user is concerned. What you're saying is that, if someone wanted a dark title bar, then they'd have to sacrifice their current accent colour, just to get it on this ONE app. 

For me personally, I don't like applying an accent colour to title bars. I keep that setting off because I find it off-putting on most apps. But as things are now, if I don't want to have a glaring white title bar on ImageGlass, that means that I have to go with the equally unappealing option of having the same, boring dark colour across _all_ of my applications (including the file explorer).

Tons of apps have a setting to choose between a dark and light mode. I have a hard time believing it would make IG unreasonably complex to do that at least.

**Comment by duckfist** [comment]
Since this is .NET Core, it's quite easy to do actually. WindowStyle must be set to "None" and a custom window style must be created, with a custom title bar and maximize/minimize buttons. This is standard procedure for any WPF desktop app that wants to look even remotely professional. The style can then be easily used by every window in the application. Dev is just lazy and still uses Windows Forms with default window styles (lol). Also, by setting the Accent Color to black in Windows Settings JUST to get dark title bars, you make text and other effects difficult to see throughout other areas of Windows since it is now black on black when using Dark Theme.

I guess my search for a competent .NET Core image viewer continues.

**Comment by fire-eggs** [comment]
> Since this is .NET Core, it's quite easy to do actually. 

Since it's "quite easy", why don't you submit a fix rather than be insulting?

The "Dev" (not me, BTW) has a real job and a real life and has to juggle priorities like any human being.

**Comment by d2phap** [comment]
Thanks @fire-eggs 
@duckfist You seem know how to implement it so well, just this, just that,... please submit a fix. Thank you.

**Comment by d2phap** [comment]
Dark mode for title bar is supported in v8.7.11.6. You may need to update your theme packs: https://imageglass.org/themes.

If you check the option `Show colour in Start, taskbar, action centre and title bar` in Windows Settings, the title bar will use the accent color.
