### ISSUE TITLE
Stays on top even when it shouldn't

### ISSUE THREAD

**Issue by SeriousHoax** [d2phap/ImageGlass#620]
### System information:
 - Windows OS version: Windows 10 Pro 1903
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. Open three or more images in a row with multiple instance turned off and often Image Glass would stay on top even when Always on top is turned off. 

### Actual behavior:

Stays on top even when it shouldn't. 
Check the attached GIF file.

### Expected behavior:

Should not stay on top

### Screenshots:

![Bug](https://user-images.githubusercontent.com/29574622/64628510-59594300-d413-11e9-98a8-9ca2bdef9f11.gif)

**Comment by d2phap** [comment]
Hi @SeriousHoax 
How often does it happen? I am unable to reproduce it though.

**Comment by SeriousHoax** [comment]
> 
> 
> Hi @SeriousHoax
> How often does it happen? I am unable to reproduce it though.

It's happening every time for me. The way I showed in the GIF. After opening first two images, Image Glass was on foreground like the way it should be but when I opened the third image, Image Glass wasn't on foreground anymore. Check the color of the title bar. Black means it's on foreground and white means it's not. Then when I click on areas outside it doesn't go away until I click back on Image Glass to make it a foreground app again.

**Comment by fire-eggs** [comment]
I'm seeing it. This is a subtle one: why does it work for the second image, but fails for the third?

From an internals perspective, this would be described as "IG is the foreground window, but does _not_ have focus". After double-clicking on the third image, IG should be both the foreground window and have focus.

**Comment by SeriousHoax** [comment]
Any update on this issue?

**Comment by fire-eggs** [comment]
Thanks for the reminder. A fix should ship with the upcoming release.

**Comment by SeriousHoax** [comment]
The new version kind of fixed the problem but it created another similar one. This happens when "Allow multiple instance of the program" is turned off. Anything after second image doesn't come to foreground maybe or something like that. Also it takes longer than before to open an image. The process has become slower with this release. Try to improve that as well. Anyway, Check this:
https://imgur.com/a/K8RHur8

**Comment by fire-eggs** [comment]
Oooh, thanks for the video! I'll have to take another look.

**Comment by VatorArt** [comment]
I don't feel like writing another thread for this issue, but I've been dealing with it since last summer, and even with constant updating this is still an issue in January, 2021.

Any updates on what caused this and how one can go about fixing it?

The way I go around this bug is by having a separate program called Alt Drag, which allows you to put any program to be always on top. By using this app, I can counter ImageGlass' always on top, and get it back to regular behavior. 
Certainly not a difficult task to do that, but it gets annoying when I have to do it every day time after time.

**Comment by mistergom** [comment]
Hello! I have the same issue here... Similar to the last @SeriousHoax video above (https://imgur.com/a/K8RHur8). The second "double-clicked" image doesn't bring IG in foreground + focus...

@VatorArt, could you please explain your temporary "fix"?

Thanks all for the great work!

**Comment by VatorArt** [comment]
> 
After couple of updates, it kinda sorted it self out. I also reinstalled windows for a different reason, so that might've helped somehow. 
Try fully reinstalling the program and see if that fixes it. 

My issue was more that any image I opened, would be stuck in " always on top " even though I didnt configure the software that way. As I said in that previous reply, I have a program called Alt Drag
So I just select the program that I want to set " always on top ", and then I press shortcut that I assigned in Alt Drag, and now the program is always on top, or vice versa. 


This is Alt Drag github page, he has good explanation on how to use it, so give it a try. 
https://stefansundin.github.io/altdrag/

Although I don't think this will help you much, unless you are also having issue with "sticky" windows.

**Comment by mistergom** [comment]
Thanks for your help!
I already tried to reinstall IG, several times, the beta version too...
I also reinstalled windows and things were quite good during the first times, and then IG continued to "bug" and stay in the background...

**Comment by mistergom** [comment]
Oh... Going deeper in other discussions, I think that it is link to :
https://github.com/d2phap/ImageGlass/issues/1195#issuecomment-997239608

> 
> With "allow multiple instances" OFF then yes, IG doesn't currently force the single window instance to the front. The exception to this is when the IG instance is minimized: the window pops front when IG restores from minimized.
> 

Argh........

**Comment by mistergom** [comment]
But why "IG doesn't currently force the single window instance to the front"?

**Comment by d2phap** [comment]
> But why "IG doesn't currently force the single window instance to the front"?

When it does not work as expected, it may be a bug and need to be fixed.
I will look into it once I have time.

**Comment by mistergom** [comment]
Thanks for your help! Keep up for the great work! ;)

**Comment by d2phap** [comment]
Fixed this in the latest build of ImageGlass Moon 8: https://imageglass.org/moon and [ImageGlass Moon 9.0 Beta 1](https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514).

**Comment by mistergom** [comment]
Great! Thanks a lot!!!
