### ISSUE TITLE
Magick.NET cache fills up free disk space rapidly

### ISSUE THREAD

**Issue by Topinambur223606** [d2phap/ImageGlass#625]
### System information:
 - Windows OS version: Windows 10, build 17134.1006
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. Open folder with two normal lightweight image files (up to 2MB) and one very heavy (50+ MB).
2. Switch many times fastly between light images **without** viewing heavy one.
3. Close app.

### Actual behavior:
App closes slowly; folder `%localappdata%\Temp` contains a lot of heavy temporary files that were created by Magick.NET and were not deleted.
Noticed it while comparing two pictures - quickly switching one to another - when free space on system drive had ended.

### Expected behavior:
Maybe those temp files shouldn't be created so many times and have to be disposed correctly.

### Screenshot:
![screenshot](https://user-images.githubusercontent.com/37106409/65436881-7f2b1280-de2b-11e9-8823-d5e0115bd15e.png)

### Additional context:
I don't know how actually app works, but nothing like that happens if there's no very large file in the same folder (5MB PSD file did nothing, 50+MB PSD file, 100+MB PNG did the trick). I guess it's something related to preloading next picture, when it's rendered or something every time it's next to be shown, even if the same thing was done a second ago; without disposal of those temp files app quickly fills a disk.

**Comment by d2phap** [comment]
Thanks @Topinambur223606 
It's nice cache!

**Comment by fire-eggs** [comment]
I've reproduced this.

If anyone is encountering this problem, the workaround is to set the ImageBooster cache count to zero. See Settings, Image tab:

![image](https://user-images.githubusercontent.com/9809727/70825747-2c6e5080-1db3-11ea-8e86-0cad847a26b1.png)

In the scenario described, if I have the cache count set to 1, I start accumulating 1G+ magick temp files (for a 281M PNG file). The mentioned "App closes slowly" behavior is due to the flushing of the huge magick temp files.

Internal note:
I believe the problem is in `StartImageBooster`: the line which reads:
`_ = img.LoadAsync(`
In the case of a very large file, Magick.NET is taking a long time to load, and creates the temp file. When the user is switching back-and-forth between images very quickly, new tasks get fired off to load an image into the cache, and this is happening faster than Magick.NET can finish the large-image load. As suggested by the OP, I believe the result is that tasks (and their associated temp file) are not getting disposed.

I think `StartImageBooster` attempts to let image loading complete with the line 
`await Task.Delay(10);`, but with a large image, a 10msec delay isn't nearly enough.

Casual hacking suggests that changing
`_ = img.LoadAsync(`
to
`await img.LoadAsync(`
appears to fix the problem, but I'm not sure of the implications. E.g. with large images, might this change slow down the building of the cache enough for the user to notice?

**Comment by d2phap** [comment]
I am unable to reproduce this, but just removed the discard `_` of C# 7 and pushed the new IG Moon: https://imageglass.org

@Topinambur223606 please help to check it again.
Thanks

**Comment by Topinambur223606** [comment]
Unfortunately, it didn't help: still a lot of large files, and heavily loaded system disk. Maybe something like a dictionary of tasks where keys are paths can help to avoid multiple creation of temp files for the same images, with cancellation, disposing, whatever will help, I don't know what magick allows to do.

**Comment by fire-eggs** [comment]
Does the workaround make things better? Or am I mistaken about that as well?

**Comment by Topinambur223606** [comment]
Yes, disabling ImageBooster solved the problem in both stable and Moon versions

**Comment by fire-eggs** [comment]
Great! Thank you for the confirm, @Topinambur223606 ! I'll have to take another look at this.

**Comment by d2phap** [comment]
@Topinambur223606 appreciate if you can check this issue still persists with IG 9?

**Comment by Topinambur223606** [comment]
Seems to be working nice and fast, issue is no longer reproducible.
