### ISSUE TITLE
Titlebar colour does not change with theme

### ISSUE THREAD

**Issue by CRISPYricePC** [d2phap/ImageGlass#630]
### System information:
 - Windows OS version: Win10 1903
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. Open ImageGlass
2. Change theme to dark (I have tested with multiple including 2017 Dark and Windows 10 Dark)

### Actual behavior:
Title bar colour remains brightly coloured

### Expected behavior:
Title bar colour should change to reflect the theme selected

##### Actual behaviour:
![image](https://user-images.githubusercontent.com/16229426/66075514-b1d3ba00-e553-11e9-9dfa-4aabcddcde59.png)
##### Expected behaviour:
![image](https://user-images.githubusercontent.com/16229426/66075549-c617b700-e553-11e9-99ce-299dedd87c2b.png)

**Comment by d2phap** [comment]
Thanks @CRISPYricePC for the issue, ImageGlass does not support changing color of title because it uses Windows title bar (not a customized title bar).
To make the title colorful, you should switch on the option in Settings > Personalisation > Colour: 
- [x] `Show colour in Start, taskbar, action centre and title bar`

![image](https://user-images.githubusercontent.com/3154213/66095288-9dca9f80-e5c9-11e9-808c-b141388bb797.png)

Also, there was already a request for this feature, posted in #595. I will close this as it is a duplication.

**Comment by d2phap** [comment]
Dark mode for title bar is supported in v8.7.11.6. You may need to update your theme packs: https://imageglass.org/themes.

If you check the option `Show colour in Start, taskbar, action centre and title bar` in Windows Settings, the title bar will use the accent color.
