### ISSUE TITLE
Option to display embedded jpg preview from RAW

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#646]
From https://groups.google.com/forum/#!topic/imageglass/N6UHHH9ZIvA

Would it be possible to have this software read the embedded jpg preview in raw files rather than the full file itself? Programs such as FastImageViewer do this but it seems that's no longer being maintained. My raw files are 50mb each so scrolling through entire full raw images, especially if it's coming over the network from my nas too slow to be functional, with software that reads embedded previews this works just fine.

**Comment by atomicwrites** [comment]
Hi, I see this was marked in progress and then the label was removed, is it because it is implemented or no longer being, considered? I would like this option for two reasons, first if I'm just looking through the raw files I will usually prefer to see the camera processed JPEGs rather than the unprocessed RAWs (RW2 in my case) because they just don't look good. If I want to work with the RAW I will be in my photo editor not a viewer. The other reason is that even on a Ryzen 5 PC (not the fastest in existence but way above average) scrolling through the RAWs takes about 3 seconds of processing per image, it looks to me like this is because it is a single threaded process.

**Comment by d2phap** [comment]
[IG v9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416) shows the embedded preview while waiting the full RAW data being loaded.
If you want to view the embedded preview only, set `UseEmbeddedThumbnailRawFormats` to `true` in `igconfig.json`

See #1290, #1293
