### ISSUE TITLE
Installing to a folder which "looks like a file" causes config / startup problems

### ISSUE THREAD

**Issue by Splike** [d2phap/ImageGlass#676]
### System information:
 - Windows OS version: Windows 10 (build 1909) x64
 - ImageGlass version: 7.5.1.1 x64 (Portable)

### What happens:
**Location:** `C:\Users\XXXXXXX\OneDrive\Programs\[Portable] ImageGlass v7.5.1.1\`
**Behavior:** Starting `ImageGlass.exe` from this location, will spawn the ImageGlass process and immediately terminate itself.

**Location:** `C:\Users\XXXXXXX\Desktop\[Portable] ImageGlass v7.5.1.1\`
**Behavior:** Starting `ImageGlass.exe` from this location, will start the first-time setup.

### What should be done?
Let ImageGlass (especially the portable version), be able to launch from paths that are longer than the current maximum.

**Comment by fire-eggs** [comment]
Just to clarify: does this mean you've installed ImageGlass to your OneDrive?

>Location: C:\Users\XXXXXXX\OneDrive\Programs\[Portable] ImageGlass v7.5.1.1\

I ask because I'm able to run IG 7.5.1.1 from this folder with no problem:
`C:\Users\Kevin\Desktop\A relatively long folder name\another longer folder name\[Portable] ImageGlass v7.5.1.1`

So it's not the path length that is likely to be the issue.

**Comment by Splike** [comment]
Not really installed, but rather just placed the contents of `ImageGlass_7.5.1.1_x64.zip` in my `OneDrive\Programs` folder. I run all my portable programs from here.

**Comment by fire-eggs** [comment]
OK, I'm going to have to try under OneDrive. In the meantime, you might try copying igconfig.xml from the folder where you successfully ran IG to the OneDrive folder.

**Comment by Splike** [comment]
That actually seems to have solved the problem!

The `igconfig.xml` file was completely empty. So doing what you said, now starts ImageGlass without any error.

**Comment by Splike** [comment]
Upon further inspection, it doesn't seem to be running in "portable mode" anymore.

The Configuration directory is set to `C:\Users\XXXXXXX\AppData\Roaming\ImageGlass`, with no way for me to change it to a folder inside my portable directory.

**Comment by fire-eggs** [comment]
OK, we've solved one issue, and found another. I've seen the `AppData\Roaming` behavior myself - we reworked the config file a bit for this release, and seem to have missed a few things.

**Comment by fire-eggs** [comment]
I had to refresh my memory about how the "portable" mode works with the config file.

What you've stumbled into (and I have confirmed) is a bug where IG decides it is _not_ in portable mode, if the folder name "looks like" a file name.

I.e. because you placed IG into a folder called `[Portable] ImageGlass v7.5.1.1`, IG got confused and decided portable mode wasn't possible.

So if you rename the folder so that it doesn't look like it has a "file extension", e.g. `[Portable] ImageGlass v7_5_1_1`, then IG will stop using `AppData\Roaming`.

Not ideal but hopefully a temporary workaround until this problem is solved.

Thank you for your patience and willingness to try various tests!

**Comment by Splike** [comment]
No problem, thank you for helping me getting it up and running!

With regards to the empty `igconfig.xml` in OneDrive, I think the issue actually lies with having a period in the folder name and not with OneDrive.

I extracted the contents of `ImageGlass_7.5.1.1_x64.zip` into the following location:
`C:\Users\XXXXXXX\OneDrive\Programs\[Portable] ImageGlass v7_5_1_1`, and was able to start it without any problem.

Your commit, which lets the startup directory contain periods, might actually fix everything mentioned in this thread.

**Comment by fire-eggs** [comment]
Glad to hear it! At least you have a work-around for the moment!

**Comment by d2phap** [comment]
Fixed this bug in the latest build of ImageGlass Moon
https://imageglass.org/moon
