### ISSUE TITLE
TGA images are rendered upside-down

### ISSUE THREAD

**Issue by tgt3D** [d2phap/ImageGlass#679]
### System information:
 - Windows OS version: Windows 10 Pro 1903
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Start ImageGlass by opening a TGA image or load a TGA image in ImageGlass with Ctrl+O
2. Observe the image is rendered upside-down

### Actual behavior:
TGA images are rendered upside-down in ImageGlass.

### Expected behavior:
All images formats should be rendered in the correct orientation.

### Screenshots:
[TGA image of letter 'A' rendered in ImageGlass](https://i.imgur.com/3K0i829.png)

**Comment by fire-eggs** [comment]
I have downloaded several TGA files off the interwebs and ImageGlass shows them "correctly".

Could you please provide a TGA file which shows "upside down".

**Comment by fire-eggs** [comment]
Although there is a problem with viewing 32 bit TGA files.

**Comment by fire-eggs** [comment]
arturodelpozo@gmail.com provided this image.

[test.zip](https://github.com/d2phap/ImageGlass/files/4097769/test.zip)

**Comment by fire-eggs** [comment]
Confirmed this is a change in behavior of ImageMagick / Magick.NET. IG will need to revert to Magick.NET 7.14.5.0 in order to solve this.

Reverting from 7.15.0.0 should be "safe" for IG as the bugs we've reported against Magick.NET are either fixed in 7.14.5.0 [Magick.NET issue 528] or we've not made use of the fix in 7.15.0.0 yet [Magick.NET issue 538].

**Comment by fire-eggs** [comment]
Fixed.

**Comment by d2phap** [comment]
ready in ImageGlass Moon https://imageglass.org/moon
