### ISSUE TITLE
Option to change the displayed date in title bar

### ISSUE THREAD

**Issue by shioku** [d2phap/ImageGlass#687]
The displayed date in the title bar is the creation date of the file.
A option to change that to the modified date or better DateTimeOriginal (EXIF Data) would be nice.

**Problem:**
For Pictures the displayed date and time is the time they where moved from the camera to the pc (creation time) and not when they where taken (modified date / DateTimeOriginal (EXIF Data)).

Following picture was taken at 28.11.2019 / 15:25:37 but ImageGlass shows it as 20.01.17 / 14:15:11.

**ImageGlass**
![grafik](https://user-images.githubusercontent.com/55065907/72616424-339af800-3937-11ea-902d-acfef6747338.png)

**IrfanView**
![grafik](https://user-images.githubusercontent.com/55065907/72616438-3f86ba00-3937-11ea-87ef-a3e55c737f78.png)

**Comment by eamonn0** [comment]
I would like to see also ability the date to be the "modified" and "taken" the picture time, instead of the "creation" time. That make more sense for me.

**Comment by dj-si** [comment]
I also support this change to show Date Taken in the title bar instead of when the file was created. Currently I have to keep switching to another app to check when a photo was actually taken, which is rather annoying.

**Comment by fire-eggs** [comment]
> Currently I have to keep switching to another app to check when a photo was actually taken, which is rather annoying.

As a better workaround, I suggest you try Ctrl+I to show image properties. ImageGlass will show the Windows File properties display, with the Details tab foremost:

![IG](https://user-images.githubusercontent.com/9809727/76009195-d22aea80-5ede-11ea-9dec-46611c69e895.PNG)

But I agree, better title bar customization would be good to have!

**Comment by dj-si** [comment]
> As a better workaround, I suggest you try Ctrl+I to show image properties. ImageGlass will show the Windows File properties display, with the Details tab foremost:
> 

Thanks Kevin! I actually found this shortcut after I posted my previous comment, but although it's easier than switching apps, it's still not as convenient as having the Date Taken visible in the title bar.

**Comment by d2phap** [comment]
This feature request is implemented and shipped in ImageGlass Moon
https://imageglass.org/moon

### ImageGlass now displays the date time information of the viewing image in this priority:
#### 1. If `DateTimeOriginal` value from Exif is found, display it with suffix `(o)`.
![image](https://user-images.githubusercontent.com/3154213/77556596-b326e380-6ef3-11ea-9b28-0ae5daca8c7c.png)

#### 2. Otherwise, if `DateTime` value from Exif is found, display it without suffix.
![image](https://user-images.githubusercontent.com/3154213/77556674-c5a11d00-6ef3-11ea-8895-651a0039367e.png)

#### 3. Otherwise, display `LastModifiedTime` of the file with suffix `(m)`
![image](https://user-images.githubusercontent.com/3154213/77556565-a7d3b800-6ef3-11ea-804d-8dc46b45c8df.png)
