### ISSUE TITLE
Suggestion: double-click zoom (for small images)

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#748]
Hello,
Please add double-click zoom feature (like windows photos)
Similar to: #147 and #86
# Screenshots
## Windows 10 Photos
![Photos](https://user-images.githubusercontent.com/23485114/79858221-53353700-83e4-11ea-8917-92fef3f4da4e.gif)
## ImageGlass
![ImageGlass](https://user-images.githubusercontent.com/23485114/79858230-55979100-83e4-11ea-9e2b-0495bf82581d.gif)

**Comment by vertigo220** [comment]
Agreed. The problem is that it won't zoom past 100%. So if I'm viewing an image that's taking up the whole window, but I want to zoom more to zoom in on a particular spot, I have to use the zoom in function, which is much more tedious. It's a lot easier to just double-click and have it zoom in on the part double-clicked. Granted, this can get a bit complicated, because if the image is smaller than the window, it could just zoom to the size of the window, but what if the user wants it zoomed in more? Or if it's the size of the window, what then? I would suggest that in the first situation, it zooms in to the size of the window if the user just double-clicks, whereas if they use some other method, such as those discussed in issues #471 and #953, then it would just zoom based on their further input. And if it's already taking up the whole window (or perhaps even most of it), then it could zoom an extra set %, e.g. 25% more, and this could be a setting so the user can choose how much. It could even allow for something like a separate zoom in and zoom out amount, and zoom-in could be tied to double-left-click and zoom out to double-right-click, so the user could set zoom in to 25% and zoom out to 10%, so double-left-clicking twice would zoom from e.g. 100% to 125% then 150%, then double-right-clicking once would zoom out to 140%.

**Comment by d2phap** [comment]
@xmha97 
You can do this in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904).

See more details and example here: https://github.com/d2phap/ImageGlass/issues/991#issuecomment-1238130837

**Comment by xmha97** [comment]
Thanks 🌹❤️
