### ISSUE TITLE
Images won't open in config.xml presence

### ISSUE THREAD

**Issue by siomekziomek** [d2phap/ImageGlass#765]
### System information:
 - Windows OS version: Windows 10 v1909
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Create folder with image file associated with IG and .xml file named "config" at the same location.
2. Try to open the image.

### Actual behavior:
Nothing happens, IG won't start. But if xml file is deleted or renamed, image opens in IG with no problem.

### Expected behavior:
IG should start.

### Additional context:
"RMB -> Open with -> ImageGlass" works nonetheless.

**Comment by d2phap** [comment]
I just tried, ImageGlass can still open.
Can you give more details or steps?

Thank you

![image](https://user-images.githubusercontent.com/3154213/80734455-c7d54780-8b41-11ea-9838-f1547104ad6e.png)

**Comment by siomekziomek** [comment]
Sorry, I don't know what else to say. It behaves exactly like I said. When I try to open the image, cursor just thinks for a second and that's it. I tried with different locations, folder contents, image types, config contents (it can even be empty file), no difference. And once config is renamed, moved or deleted, image opens immidiately.

![obraz](https://user-images.githubusercontent.com/57877784/80735335-d5bea480-8b10-11ea-8f6b-6b4a499088cd.png)

**Comment by siomekziomek** [comment]
Hmmm, it works in presence of IG theme config though. If I had to guess, I'd say IG confuses them somehow?

**Comment by DemonLord98** [comment]
I have the same issue. I tested it with two computers.
IG seems to work just fine with commit [24750e6](https://github.com/d2phap/ImageGlass/commit/24750e6f5c1a55c4020404f5dc968951af5553ed). The problem probably starts with [6ce677d](https://github.com/d2phap/ImageGlass/commit/6ce677da4101d125db69c0b2e147dc882dc60825) (I couldn't build it due to some error hence probably, but the next commit [9c51ff9](https://github.com/d2phap/ImageGlass/commit/9c51ff9a61426fa824530894bee43a95a6521e86) builds just fine).

**Comment by fire-eggs** [comment]
Interesting bug. Easy enough to repro. Thank you for the report!

The trick is that the config.xml file must be _empty_, or _invalid_. The problem does not manifest if a correct config.xml file is used.

The first problem is in Theme.cs, LoadTheme().

When double-clicking on a file to open it using IG as the associated viewer, the current working directory for IG is the folder where the image resides. The _first_ time LoadTheme() is invoked, the input path is empty. In this case, if a (bogus) file named config.xml is in the image folder, it will be found, IG will try to use it, throw an exception, and shut down.

So issue #1: LoadTheme needs exception handling for a bogus XML file.

[Side note: when IG is invoked via RMB->Open With..., the current working directory is "C:\windows\system32". So an empty/bogus config.xml file in that folder would cause the same problem.]

Issue #2: the _second_ time LoadTheme() is called, the full path to the Themes folder relative to the App Directory is provided. So, why is LoadTheme() called twice? Why is the first call with an empty path? [In my case I'm not using the Default theme.]

Issue #3: what happens if the theme config.xml file in the installation folder is deleted or corrupted? IG behaves the same as in the original report: falls over silently.

As I'm not in a position to attempt to solve any of these right now, here are my suggestions:

- re-examine passing an empty path to LoadTheme, or using the current working directory
- re-examine calling LoadTheme twice
- add try / catch in theme loading. Attempt to use the install folder theme if the provided theme path fails
- consider using a less generic filename instead of "config.xml", e.g. "igtheme.xml"
- consider a diagnostic message when IG encounters a "I can't continue" scenario. In this case, something along the line of "theme config file at location <folder> is corrupt or missing", rather than fail silently

**Comment by DemonLord98** [comment]
@fire-eggs I worked on your forth suggestion. changed every reference from `config.xml` to `igtheme.xml` and changed the file name under path `ImageGlass\Setup\Assets\DefaultTheme\` to `igtheme.xml`.
I will create a pull request in **develop** branch since I don't know if this will break something else.

**Comment by d2phap** [comment]
Shipped in IG Moon: https://imageglass.org/moon
