### ISSUE TITLE
Lock Pan (Like "Lock Zoom Ratio", but for position/location/pan)

### ISSUE THREAD

**Issue by JohnTravolski** [d2phap/ImageGlass#795]
### Is your feature request related to a problem? Please describe.

It would be helpful if there was a way to lock the position of the view when switching between images. For example, suppose I want to compare the top left corner of two images (of the same dimensions) very closely. Although lock zoom ratio keeps the zoom level the same for both, the view always resets to the center of the image when switching between the two. This makes it impossible to compare corners of images closely (at a high zoom level).

### Describe the solution you'd like

It would be nice if there was a feature that would keep the camera's position/location/pan (whatever you call it) the same when switching between images that are the same resolution (my feature doesn't really make sense for images that are different resolutions). It would be an additional button you could toggle on and off.

### Describe alternatives you've considered

None

Here's a video showing the existing behavior that I don't like:
https://www.youtube.com/watch?v=VIo4HojdrSc&feature=youtu.be

**Comment by Canwail-Modular** [comment]
It seems that feature is already implemented, just that there is no way to enable it. If you set the `isKeepZoomRatio` parameter in the `NextPic` method/function in `Source/ImageGlass/frmMain.cs` to true it does exactly what you (and I) are looking for. I would submit a PR, but I think this is something that should be toggled in the top bar of the Image Viewer (instead of the settings menu) and I dont think there is a proper icon for that. 

One problem that I noticed is that when zoomed in and switching between images with arrow keys, it pans ever so slightly to the right/left. This could probably be fixed by being able to disable arrow key panning when having this "Keep Zoom/Pan" mode enabled or just in the settings. (Or just not using arrow keys at all and instead use PageUp/PageDown)

**Comment by Unknow0059** [comment]
> One problem that I noticed is that when zoomed in and switching between images with arrow keys, it pans ever so slightly to the right/left

I came to the github to report this as an issue of it's own, but you have written it here. 
I had noticed the issue was not present when using the mouse to click through Thumbnails.
If you want to give this issue visibility you should probably make it an issue for it.

> Or just not using arrow keys at all and instead use PageUp/PageDown

In the meantime this will serve as a workaround.

**Comment by Unknow0059** [comment]
@Canwail-Modular 
> One problem that I noticed is that when zoomed in and switching between images with arrow keys, it pans ever so slightly to the right/left

I came to the github to report this as an issue of it's own, but you have written it here. 
I had noticed the issue was not present when using the mouse to click through Thumbnails.
If you want to give this issue visibility you should probably make it an issue for it.

> Or just not using arrow keys at all and instead use PageUp/PageDown

In the meantime this will serve as a workaround.

**Comment by mirh** [comment]
I kinda think this is part of a bigger problem with position resetting #979

Maybe there should just be a setting "what default position do you want in images".

**Comment by SB2020-eye** [comment]
So @canwail , when you say, "If you set the isKeepZoomRatio parameter in the NextPic method/function in Source/ImageGlass/frmMain.cs to true it does exactly what you (and I) are looking for," how do I set this setting you are referencing?

**Comment by d2phap** [comment]
Implemented in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225). Lock zoom ratio also keeps the position for the next image.

**Comment by mirh** [comment]
Cool, I don't think I had ever found a tool allowing to do zoomed-in comparisons. 
But it seems like lock zoom ratio is applied for every scaling mode except "auto zoom".
