### ISSUE TITLE
Images are opened from cache location if located on phone

### ISSUE THREAD

**Issue by JohannesDev** [d2phap/ImageGlass#797]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Connect an android phone to PC
2. Navigate to image folder
3. Open image
4. Path is now opened from some cached location instead of the actual external path

### Actual behavior:
If I open the image like in the steps above described, I get a path like _C:\Users\\[UserName]\AppData\Local\Microsoft\Windows\INetCache\IE\\[Some Number]_. Also if I have multiple images in the directory, most of them are not loaded and can't be navigated to with the "next image" action.

### Expected behavior:
I should get a path like _This PC\\[Phone Name]\SD card\DCIM\Camera_. 

### Additional context:
My guess is that this happens because phones are not assigned [drive letters](https://superuser.com/questions/1157661/how-to-mount-an-android-smartphone-as-a-drive-in-windows), although this is just a wild guess.

**Comment by d2phap** [comment]
Hi @JohannesDev 
Windows "downloaded" the images to the cache folder, and then sent them to ImageGlass.
Nothing can be done in ImageGlass side.

**Comment by JohannesDev** [comment]
Thanks for your reply @d2phap. That makes sense, I don't understand why windows handles this situation like that. Maybe it would be possible to get access to the android device anyway by navigating manually to it (haven't looked into how Net/Windows handles file access to an MTP/PTP device) but I guess that would be a lot of work to makes sure it works without any problems.

What are your thoughts on this? I don't have a lot of time right now but if you are interested I could look into this in the future. Although like I said, I don't know a lot about how MTP/PTP devices are handled on windows and if this would even be possible. Initially I thought android devices are so popular that accessing the storage should just work because it is already handled by the appropriate windows API/library.

**Comment by d2phap** [comment]
I think the main reason is because Windows tries to speed up the files from MTP which is usually slow.

https://en.wikipedia.org/wiki/Media_Transfer_Protocol#Performance
> Performance
(-) MTP allows **no parallelism**, unlike USB mass storage or NAS. MTP has been built to **only allow a single operation simultaneously** (for example: read, write or delete operation), while no other operation can be executed until the previous operation is complete.
(-) **Limited** support for transferring parts of files, such as blocks or byte ranges (see § Direct modification and partial transfer features).
(-) **Limited** support for direct modification of files (see § Direct modification and partial transfer features). To modify a file or its metadata, the whole file may need to be copied out of the device and reuploaded, which takes a long time for a large file or directory, and blocks the device for other operations in the meantime. Google's MTP implementation in Android includes extensions to deal with this limitation; however, these extensions must be supported by the host operating system.[8][9]
(-) Loading longer file lists (thousands of items) and "preparing" for transferring files might **take longer** than the file transfer itself.

**Comment by JohannesDev** [comment]
Well that's to bad but thanks for you answer. I'm closing this.
