### ISSUE TITLE
Portable mode?

### ISSUE THREAD

**Issue by jsieler** [d2phap/ImageGlass#82]
Would be really nice to have portable mode for the app. Setting stored in config within app folder too. Possible?

**Comment by d2phap** [comment]
Hi @jsieler 

Thanks for your suggestion. :)

**Comment by ZIEXED** [comment]
Any update here?

**Comment by d2phap** [comment]
Hi,

I'm still working on :)

**Comment by d2phap** [comment]
Portable mode is supported in the upcoming release.
User can enable it by:
- `Enable Portable mode` option in Settings dialog
- `--portable` parameter to `ImageGlass.exe` file.

This is ImageGlass Moon - a nightly build for testing: www.imageglass.org/upload/moon/ImageGlass_3.x_04032017.zip

![image](https://cloud.githubusercontent.com/assets/3154213/23576092/6460a6ac-00d6-11e7-8584-a221d541ba21.png)

**Comment by feidaman** [comment]
Hi, I've checked the "Portable Mode" option but the program still writes data to the registry. Usually, applications that can run in portable mode detect the presence of a certain file in the .exe directory. For example, Media Player Classic Home Cinema will check for the presence of a file named **mpc-hc.ini**, if the file exists the program assumes portable mode, else the program will write its settings to the standard user data folder. I see there's a file named **igconfig.xml** next to ImageGlass.exe, but this file is re-generated each time I run the program, and settings get written to the registry whether or not this file exists. Help! 👍

**Comment by feidaman** [comment]
Latest update still writes settings to the registry even if Portable Mode is checked.

**Comment by d2phap** [comment]
Hi @feidaman 

Sorry I missed your comment https://github.com/d2phap/ImageGlass/issues/82#issuecomment-314108741
As you mentioned, ImageGlass is not true portable because it needs to read `IsPortableMode` key in registry. 

The problem is that Windows doesn't allow app to write files to Program Files folder. This makes the app cannot write config file into installed folder.

My plan is to create versions of ImageGlass: 1 installer and 1 ZIP file.
- The Installer version uses Registry to store configs.
- The Zip version writes configs to XML file.

This can resolve the shortage for Portable mode. However, as a result, it makes ImageGlass fragmented.

Back to your idea, I will investigate to see how it works.
Thanks a lot!

**Comment by feidaman** [comment]
Hi, I think having two separate versions is unnecessary. What you say is correct, Windows prevents the program from writing into the installation folder. BUT, the reality is, nobody puts a portable app in C:\Program Files. Most of us "portable app fans" have a folder, perhaps in D:\Portable, where we put all our portable apps. This way our apps and settings stay even if we reinstall the OS.

When the app is installed to C:\Program Files, if the user instructs it to run portably (by checking the option in the settings) and the app fails to create the XML file due to write restrictions, the app could simply notify the user about this error with a small pop-up and continue to run as non-portable. If the XML file already exists, then the checkbox in the settings is pre-checked when the program runs.

**Comment by d2phap** [comment]
`IsPortableMode` key is removed.
ImageGlass will try to run in Portable mode by default; if not, the configs will be written in registry.

The implementation is moved to `develop` branch

**Comment by anewuser** [comment]
Are you going to offer  .zip or .7zip downloads for the upcoming releases, so that we don't have to download the installer in first place?

**Comment by d2phap** [comment]
Hi @anewuser 
Of course I will offer a ZIP portable version beside Installer version :)

**Comment by jsieler** [comment]
Is there some nightly build available?

**Comment by d2phap** [comment]
Hi @jsieler 
You can try it here:
http://www.imageglass.org/moon

**Comment by jsieler** [comment]
Thanks!

2017-10-11 15:51 GMT+02:00 Phap Dieu Duong <notifications@github.com>:

**Comment by smaragdus** [comment]
@d2phap 

Hello, I uninstalled **ImageGlass** version **3.2.0.16** (yes, I have missed 3 major releases), deleted

`HKEY_CURRENT_USER\Software\PhapSoftware\ImageGlass`

from registry and run **ImageGlass** version **4.5.11.14** and I can confirm that this "Moon" release seems to be truly portable- it does not create any registry keys any more, good work, thanks!

What I miss in **ImageGlass** is support for [APNG](https://en.wikipedia.org/wiki/APNG) files. Do you plan to add support for **APNG** (Animated Portable Network Graphics) files?

**Comment by d2phap** [comment]
Hi @smaragdus 
Currently ImageGlass just opens `APNG` format as static image, need more work for animated format.
The stable version of 4.5 is coming in couple days.

**Comment by smaragdus** [comment]
@d2phap 
Yes, I noticed it shows only the first frame of an animated APNG file.
Something unrelated, it seems that in portable mode themes cannot be used- Extension Manager installs themes in AppData but they cannot be loaded. It would be nice if in portable mode Extension Manager installs themes in program folder (perhaps creating 'Themes' sub-folder). Would this require too much work?
Regards and happy coding!

**Comment by d2phap** [comment]
@smaragdus 
There will be a big update for Theme feature in v5.0 so I gonna move the extension codes into the app, it will be easier to manage and can be localized by language packs.
As you can see, the extension is removed from website menu. It means no longer support for it.

**Comment by smaragdus** [comment]
@d2phap 

Good idea. I will keep an eye on [Moon Releases](http://www.imageglass.org/moon) for new stuff for testing. If I encounter any problems I will report them.

One last question- have you thought of adding 'Favourites'- a list of often browsed folders for quick access? I suppose this may be handy. I imagine it as a button in the tool-bar with a drop-down menu to open bookmarked folders- 'Bookmarks', 'Favourites', 'Quick Folders', the name does not matter.

**Comment by d2phap** [comment]
@smaragdus 
There was a placeholder on UI code for this feature since v3.0. But it was not developed until now :)

**Comment by RoyiAvital** [comment]
Is the ZIP in current releases a portable version of the program?

**Comment by fire-eggs** [comment]
Yes, the ZIP files in the releases is the portable version.

Alternatively you can use the [website](https://imageglass.org/release/imageglass-8-2-6-6-june-32).
