### ISSUE TITLE
UWP

### ISSUE THREAD

**Issue by mikkolukas** [d2phap/ImageGlass#828]
I saw your announcement that you want to change to UWP.

Just for you to be aware before going deep into that path.
The platform contains a risk of being de-facto deprecated and it may survive or not.

**Example articles here** (more on google searches):
2019-05-08: [Microsoft Confirms UWP is Not the Future of Windows Apps](https://www.thurrott.com/dev/206351/microsoft-confirms-uwp-is-not-the-future-of-windows-apps) [thurrott.com]

2019-05-30: [Why UWP is, and isn’t, dead – the dream is gone, but the code lives on](https://www.onmsft.com/editorial/why-uwp-is-and-isnt-dead-the-dream-is-gone-but-the-code-lives-on) [onmsft.com]

2020-01-13: [Another blow to UWP as Microsoft could soon deprecate the Windows 10 Stores for Business and Education](https://www.notebookcheck.net/Another-blow-to-UWP-as-Microsoft-could-soon-deprecate-the-Windows-10-Stores-for-Business-and-Education.450040.0.html) [notebookcheck.net]

**Comment by d2phap** [comment]
Hi @mikkolukas 

Thanks for your post.
I have read all of these articles while researching and finding a more efficient platforms for IG. Which I tried were WPF, Electronjs, UWP... And I found that UWP is more optimal in memory usage, plus a flexible UI.

Apparently, there are very less UWP apps comparing to Win32 apps. It's because UWP is still new to developers, and also has lots of restrictions. In recent years, we have been hearing UWP is being deprecated when Microsoft had given up MS Edge (legacy) and moved to Chromium-base Edge. These concerns are true. However, as what I can see, they are still moving old settings to the new UWP Settings app. And the most recent important project, Windows Terminal, is also UWP.

I got some questions about this as I haven't made an official announcement about roadmap on IG website yet. I'm waiting for the first alpha version of IG Preview, in that time, people will have something to try it.

### The "draft" roadmap will be:
- Both apps (WinForms IG and UWP IG) will live together.
- WinForms IG is not abandoned, it will still receive updates, features. 
- UWP IG will progressively have the features of WinForms IG, with a modern, flexible UI.
- There will be alpha, beta versions of UWP IG for people who want to try (updated at https://github.com/d2phap/ImageGlass-Preview).

**Comment by d2phap** [comment]
Published roadmap at: https://www.patreon.com/posts/imageglass-and-39849218

**Comment by Poopooracoocoo** [comment]
>However, as what I can see, they are still moving old settings to the new UWP Settings app

They just started doing that again after a three year hiatus and they've only moved a miniscule fraction of the disk management settings. Microsoft hasn't proven that they will be doing any more.

>And the most recent important project, Windows Terminal, is also UWP.

It's not pure UWP + WinUI. It's a sort of hybrid app.

Skype went from native to React Native to Electron. The Xbox and MS Store apps are React Native apps. MS Teams is an Electron app. PowerToys is a win32 app that uses WinUI 3. 

I understand why you went with UWP but I'm wary of its future.

**Comment by e-t-l** [comment]
What's the current status of this? I see the [Imageglass-Preview](https://github.com/d2phap/ImageGlass-Preview/) repo is archived. Is the current version of Imageglass on the Microsoft Store a UWP?
