### ISSUE TITLE
Some gifs, when zoomed to fit/height/width/fill, pause slideshow countdown + cause toolbar bugs

### ISSUE THREAD

**Issue by the-nelsonator** [d2phap/ImageGlass#875]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Open this gif: ![tendies](https://user-images.githubusercontent.com/23157710/94379670-c6a34900-00e6-11eb-85fa-b2d539993d71.gif)
2. Start slideshow (same thing happens in full screen and windowed slideshow)
3. Open toolbar (or just use the # shortcuts for step 4)
4. Zoom to fit/height/width/fill while still on gif

### Actual behavior:

Countdown timer is paused. If you switch to auto zoom, it works normally. Also bugs out the toolbar (see screenshots)

### Expected behavior:

Countdown timer to count down as normal.

### Screenshots:

Don't have giffing/recording software to document the countdown pausing, let me know if it's needed.

Toolbar issues:

Toolbar is gone after going into slideshow and back out while still on bugged gif.
Before opening slideshow:
![image](https://user-images.githubusercontent.com/23157710/94379733-1da91e00-00e7-11eb-85e0-20ee90ce78b8.png)
After closing slideshow:
![image](https://user-images.githubusercontent.com/23157710/94379742-226dd200-00e7-11eb-977a-c6f4362c1c8c.png)

Also even before opening, if you're zoomed to fit, hovering tooltips/help text don't show up, compare to this:
![image](https://user-images.githubusercontent.com/23157710/94380040-bdb37700-00e8-11eb-9581-7248ae96f2a5.png)

**Comment by fire-eggs** [comment]
Not able to repro in Win7 (native) or Win10 (virtual machine). I'll have to leave it to Phap to see if it can be repro-ed in a native Win10.

**Comment by fire-eggs** [comment]
Wasn't able to repro with the OP's gif, but can repro using the attached GIFs. Possible the issue doesn't manifest when using only one file in the slideshow. May be related to issue #344 .

![_____Boat2-800-Micael-Reynaud](https://user-images.githubusercontent.com/9809727/95102676-ab959200-0701-11eb-910f-b6c841128296.gif)

![animatic_jotto](https://user-images.githubusercontent.com/9809727/95102958-05965780-0702-11eb-89ef-a66c11758d68.gif)

**Comment by fire-eggs** [comment]
Note I'm using IG 7.6.9.13 and Win7 (Native) and reproducing.

This is hard to repro / capture. If I start the slideshow with particular GIF file, then
1. The F11 tooltip doesn't disappear
2. The timer doesn't appear
3. The countdown doesn't happen (slideshow doesn't advance)

If I manually advance the slideshow (PageDn) then it acts as normal. Then back to the first image (PageUp): the countdown does appear but doesn't change.

I do think this is similar to #344: the GIF is so CPU intensive that ImageGlass doesn't get any cycles to update the GUI / timer. With some of the GIFs I'm using, changing the size (as suggested by the OP) makes no difference.

I've put a screen recording (test.gif) and some problematic GIFs in my [Google Drive](https://drive.google.com/drive/folders/1s4dKaD-et5s2qVj34FJdkwUdpdUbbR1g?usp=sharing).
(Unfortunately, I cannot give a frame-by-frame breakdown of the recording because IG's Page Navigation does not do frame stepping.)

**Comment by d2phap** [comment]
Since v9 moves Slideshow to a separate window. It should be not an issue.
