### ISSUE TITLE
IG Broken after Upgrade

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#887]
Mentioned in Google group, no version/platform details provided.

### System information:
 - Windows OS version:  as of yet unknown
 - ImageGlass version:    as of yet unknown

### To Reproduce
1. Got upgrade prompt.
2. "Went for it"

### Actual behavior:
Cannot open any pictures after update.

Error message:
ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported.
Magick.NET-Q16-AnyCPU: The type initializer for 'NativeMagickSettings' threw an exception.

### Expected behavior:
IG should work fine after update.

### Screenshots:
N/A

### Additional context:
User claims that .NET Framework 4.8 is already installed. The error suggests that Magick.NET is out-of-sync w/ ImageGlass.  Need to confirm that an update correctly upgrades Magick.NET. May have to try the installer/portable, x86/x64 variations, pending any further details from the user.

**Comment by d2phap** [comment]
Closed due to no further info provided

**Comment by asheroto** [comment]
This issue is still present. Brand new Windows 10 installation on a VM - issue present. Brand new Windows 10 installation on a laptop - issue present.  In addition, the buttons at the top are messed up / missing.

Here's what it looks like....
![asdf](https://user-images.githubusercontent.com/49938263/173176656-7413e466-5e24-4add-9670-60f84c1409da.png)
