### ISSUE TITLE
Refresh button doesn't work

### ISSUE THREAD

**Issue by justanotheranonymoususer** [d2phap/ImageGlass#904]
If a photo is removed, the old version is cached (that's OK), but the reload button doesn't work.
Video:
https://imgur.com/a/R5YHVhI

Edit: By the way, I don't know if that would work after the fix, but having F5 doing a refresh can be handy. The tooltip says the shortcut is R, but F5 is an established hotkey.

**Comment by fire-eggs** [comment]
Thank you for the excellent video showing the issue! Very helpful!

Unfortunately, you are using the "refresh" button, which merely re-draws the current in-memory image. If you had used the "reload" function (Menu\File\Reload Image, or CTRL+R) then the modified image would have been reloaded correctly.

I don't remember why "Refresh" is even necessary. This confusion / overloaded function is unfortunate.

Experimenting, I see that:
1. If the image being modified is the "active" image in IG, then it updates nicely.
2. If the image being modified is NOT the "active" image in IG, then the thumbnail updates, but:
2a. ... the image does update if it has not been loaded into the cache
2b. ... the image does _not_ update if it has been loaded into the cache

So I think if 2b. was fixed so that the image is reloaded (even if cached) when the directory watcher sees a modification, it would be a better solution.

**Comment by d2phap** [comment]
The Refresh function is designed to reset the zooming value. To totally reload the image, use Reload (Ctrl+R)
