### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#950]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Go through a bunch of gifs
2. Memory usage keeps increasing
3. Ram dies because of memory leak

Even setting Number of Images cached to 0, it manage to consume 2 gb ram as I go through the freaking gifs. Please fix.

**Comment by d2phap** [comment]
Hi @01yakiek 

Do you have any screenshots and the file that causes memory leak?

**Comment by Meowski** [comment]
I was able to reproduce this on the current develop branch.  It would seem the Bitmap class' resources are not being garbage collected after being disposed. To trigger collection I had to explicitly set Image to null at the end of the Dispose method in the ImageGlass.Heart.Img class, and on my machine that seemed to be enough to trigger collection.

As an example, after rapidly loading a few hundred gifs totaling roughly 500MB in size, my heap looked like this:

![not-null](https://user-images.githubusercontent.com/14046308/102964780-10b38500-44b2-11eb-966f-6298e1e3294e.JPG)

Repeating the experiment after setting Image to null looked like this:

![null](https://user-images.githubusercontent.com/14046308/102964812-1f01a100-44b2-11eb-967b-bbf043e112b3.JPG)

**Comment by fire-eggs** [comment]
Good catch!

GIF files are a "special case" in that IG has Windows load them instead of Magick.NET. In hindsight, I'm not surprised if that means a distinct cleanup process is required. 

TIF files are also "special cases" so I'd not be surprised if TIF files also demonstrate the problem.

Since Dispose() on Bitmap isn't always sufficient to trigger collection, that suggests the Img instances (e.g. as held in `ImgList`) might not be properly cleaned up either. Pending further digging, your fix at least eliminates the worst of the problem.

**Comment by d2phap** [comment]
Applied the fix and shipped to https://imageglass.org/moon
