### ISSUE TITLE
Touch screen support

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#96]
From https://groups.google.com/forum/#!topic/imageglass/5IMgxmzVjzU

Despite being the best display of images that I found, no commands for touch screens (slide to change image and zoom in or zoom out).
should have option to hide certain buttons, often i rotates the image by mistake, instead of switching to the next

**Comment by da3dsoul** [comment]
The left and right arrows mentioned in #448 will help quite a bit.

I'll post some research that I've done. WinForms is ancient and not well supported, so that doesn't help. WPF just works with touch, but WPF has its own issues with many things.
https://stackoverflow.com/questions/25394291/detecting-various-touch-events-in-a-winforms-app
https://docs.microsoft.com/en-us/windows/desktop/wintouch/windows-touch-samples

**Comment by wanderseeme** [comment]
Please add touch screen support, with pinch/zoom ability this software will be perfect!
- Sent from a user with heavy adoption of Windows touch screen

**Comment by d2phap** [comment]
@wanderseeme 
We have an initial touch support in https://github.com/d2phap/ImageGlass/commits/feature/Touch branch, I will merge it to develop branch for public testing (IG Moon) when it's ready.

**Comment by fire-eggs** [comment]
Touch support has been shipped!  [Try the latest build](https://imageglass.org/moon)

The following actions are available:
- swipe left/right for previous/next picture
- rotate in either direction (90-degree)
- zoom in/out at a location via spread/pinch
- zoom in/out via swipe up/down

Caveat: implemented and tested only via emulation!
