### ISSUE TITLE
customize the info shown in title bar?

### ISSUE THREAD

**Issue by SilentGene** [d2phap/ImageGlass#971]
Hi there, Thanks for developing such a useful and handy tool!

I was just wondering if there is any way to customize the information shown in the title bar? As a photographer, information such as ISO/ aperture/ shutter speed is also very important to check when browsing images. So if there is an option for us to customize which exif info we would like to be shown in the title bar, that would be perfect!

Thanks,
Heyu

**Comment by d2phap** [comment]
Thanks @SilentGene 
Currently IG does not support customizing title bar info yet.

**Comment by d2phap** [comment]
This issue is implemented in the ImageGlass Moon v9.0 beta 1: https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514.
You can customize it using the setting `InfoItems` in the `igconfig.json` file.

![image](https://user-images.githubusercontent.com/3154213/169641902-41075ced-b362-47e0-ac0f-5311c21ed1bf.png)


All the tags you can use are:
https://github.com/d2phap/ImageGlass/blob/2e3de3af3b781f661e8bfdd73736f3b988f943e2/v9/Components/ImageGlass.Base/BasicInfo.cs#L25-L39

**Comment by SilentGene** [comment]
Thanks for realizing this in the new version! However, I still wanted to ask if the information like `ISO/ aperture/ shutter speed` is possible to be shown in the title bar? It looks like there is no such options currently according to the code.

Thanks,
Heyu

**Comment by d2phap** [comment]
Hi @SilentGene, there will be more EXIF tags to show in the next release

**Comment by SilentGene** [comment]
> Hi @SilentGene, there will be more EXIF tags to show in the next release

That's exciting! Cheers, mate.
